//AutoGenerated

namespace org.w3c.dom.file
{

    public interface File : Blob
    {
        // File
        string name {get;}
        string type {get;}
        string urn {get;}
    }

}