using SharpKit.JavaScript;
//AutoGenerated

namespace org.w3c.dom.traversal
{

    using Node = org.w3c.dom.Node;

    public interface NodeFilter
    {
        // NodeFilter
//TODO: Interfaces cannot contain fields in .NET:
//        public static final short FILTER_ACCEPT = 1;
//TODO: Interfaces cannot contain fields in .NET:
//        public static final short FILTER_REJECT = 2;
//TODO: Interfaces cannot contain fields in .NET:
//        public static final short FILTER_SKIP = 3;
//TODO: Interfaces cannot contain fields in .NET:
//        public static final int SHOW_ALL = 0xFFFFFFFF;
//TODO: Interfaces cannot contain fields in .NET:
//        public static final int SHOW_ELEMENT = 0x00000001;
//TODO: Interfaces cannot contain fields in .NET:
//        public static final int SHOW_ATTRIBUTE = 0x00000002;
//TODO: Interfaces cannot contain fields in .NET:
//        public static final int SHOW_TEXT = 0x00000004;
//TODO: Interfaces cannot contain fields in .NET:
//        public static final int SHOW_CDATA_SECTION = 0x00000008;
//TODO: Interfaces cannot contain fields in .NET:
//        public static final int SHOW_ENTITY_REFERENCE = 0x00000010;
//TODO: Interfaces cannot contain fields in .NET:
//        public static final int SHOW_ENTITY = 0x00000020;
//TODO: Interfaces cannot contain fields in .NET:
//        public static final int SHOW_PROCESSING_INSTRUCTION = 0x00000040;
//TODO: Interfaces cannot contain fields in .NET:
//        public static final int SHOW_COMMENT = 0x00000080;
//TODO: Interfaces cannot contain fields in .NET:
//        public static final int SHOW_DOCUMENT = 0x00000100;
//TODO: Interfaces cannot contain fields in .NET:
//        public static final int SHOW_DOCUMENT_TYPE = 0x00000200;
//TODO: Interfaces cannot contain fields in .NET:
//        public static final int SHOW_DOCUMENT_FRAGMENT = 0x00000400;
//TODO: Interfaces cannot contain fields in .NET:
//        public static final int SHOW_NOTATION = 0x00000800;
        short acceptNode(Node n);
    }

}
