//Generated by a tool of Sebastian Loncar

namespace SharpKit.Html
{

using SharpKit.JavaScript;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields = true, OmitCasts = true)]
public partial class SVGTextPositioningElement : SVGTextContentElement
{

	// SVGTextPositioningElement
	public SVGAnimatedLengthList x {get; private set; }
	public SVGAnimatedLengthList y {get; private set; }
	public SVGAnimatedLengthList dx {get; private set; }
	public SVGAnimatedLengthList dy {get; private set; }
	public SVGAnimatedNumberList rotate {get; private set; }
}

}