//Generated by a tool of Sebastian Loncar

namespace SharpKit.Html
{

using SharpKit.JavaScript;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields = true, OmitCasts = true)]
public partial class TypeInfo
{

	// TypeInfo
	public JsString typeName {get; private set; }
	public JsString typeNamespace {get; private set; }
	public static int DERIVATION_RESTRICTION = 0x00000001;
	public static int DERIVATION_EXTENSION = 0x00000002;
	public static int DERIVATION_UNION = 0x00000004;
	public static int DERIVATION_LIST = 0x00000008;
	public bool isDerivedFrom(string typeNamespaceArg, string typeNameArg, int derivationMethod) { return default(bool); }
}

}