//Generated by a tool of Sebastian Loncar

namespace SharpKit.Html
{

using SharpKit.JavaScript;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields = true, OmitCasts = true)]
public partial class LSInput
{

	// LSInput
	public object characterStream {get; set; }
	public object byteStream {get; set; }
	public JsString stringData {get; set; }
	public JsString systemId {get; set; }
	public JsString publicId {get; set; }
	public JsString baseURI {get; set; }
	public JsString encoding {get; set; }
	public bool certifiedText {get; set; }
}

}