// Generated by SharpKit.QooxDoo.Generator
using System;
using System.Collections.Generic;
using SharpKit.Html;
using SharpKit.JavaScript;

namespace qx.ui.splitpane
{
    /// <summary>
	/// <para>The slider of the SplitPane (used during drag sessions for fast feedback)</para>
	/// </summary>
	[JsType(JsMode.Prototype, Name = "qx.ui.splitpane.Slider", OmitOptionalParameters = true, Export = false)]
    public partial class Slider : qx.ui.core.Widget
    {
		#region Properties

		[JsProperty(Name = "allowShrinkX", NativeField = true)]
		public object AllowShrinkX { get; set; }

		[JsProperty(Name = "allowShrinkY", NativeField = true)]
		public object AllowShrinkY { get; set; }

		#endregion Properties

		#region Methods

		public Slider() { throw new NotImplementedException(); }

		#endregion Methods
    }
}