/*Generated by SharpKit 5 v4.29.7000*/
$(OnReady);
function OnReady()
{
    var win=$("#window");
    var undo=$("#undo");
    undo.bind("click",function(e)
    {
        win.data("kendoWindow").open();
        undo.hide();
    });
    if(win.data("kendoWindow") == null)
    {
        win.kendoWindow(
        {
            width:"500px",
            actions: ["Custom","Minimize","Maximize","Close"],
            title:"About Josef Hoffmann",
            close:function()
            {
                undo.show();
            }
        });
    }
    win.data("kendoWindow").wrapper.find(".k-i-custom").click(function(e)
    {
        alert("Custom action button clicked");
        e.preventDefault();
    });
};
