/*Generated by SharpKit 5 v4.29.7000*/
$(OnReady);
function OnReady()
{
    var window=$("#window");
    var undo=$("#undo");
    undo.bind("click",function(e)
    {
        window.data("kendoWindow").open();
        undo.hide();
    });
    if(window.data("kendoWindow") == null)
    {
        window.kendoWindow(
        {
            width:"500px",
            actions: ["Custom","Minimize","Maximize","Close"],
            title:"About Josef Hoffmann",
            close:function()
            {
                undo.show();
            }
        });
    }
     window.data('kendoWindow').wrapper.find('.k-i-custom').click(function(e){alert('Custom action button clicked');e.preventDefault();});;
};
