// Generated by SharpKit.QooxDoo.Generator
using System;
using System.Collections.Generic;
using SharpKit.Html;
using SharpKit.JavaScript;

namespace qx.ui.mobile.navigationbar
{
    /// <summary>
	/// <para>A navigation bar widget.</para>
	/// <para>Example</para>
	/// <para>Here is a little example of how to use the widget.</para>
	/// <code>
	/// var bar = new qx.ui.mobile.navigationbar.NavigationBar();
	/// var backButton = new qx.ui.mobile.navigationbar.BackButton();
	/// bar.add(backButton);
	/// var title = new qx.ui.mobile.navigationbar.Title();
	/// var.add(title, {flex:1});
	/// this.getRoot.add(bar);
	/// </code>
	/// <para>This example creates a navigation bar and adds a back button and a title to it.</para>
	/// </summary>
	[JsType(JsMode.Prototype, Name = "qx.ui.mobile.navigationbar.NavigationBar", OmitOptionalParameters = true, Export = false)]
    public partial class NavigationBar : qx.ui.mobile.container.Composite
    {
		#region Properties

		[JsProperty(Name = "defaultCssClass", NativeField = true)]
		public object DefaultCssClass { get; set; }

		#endregion Properties

		#region Methods

		public NavigationBar() { throw new NotImplementedException(); }

		public NavigationBar(object layout) { throw new NotImplementedException(); }

		#endregion Methods
    }
}