//Generated by a tool of Sebastian Loncar

namespace SharpKit.Html
{

using SharpKit.JavaScript;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields = true, OmitCasts = true)]
public partial class DocumentCSS
{

	// DocumentCSS
	public CSSStyleDeclaration getOverrideStyle(Element elt, string pseudoElt) { return default(CSSStyleDeclaration); }
}

}