//Generated by a tool of Sebastian Loncar

namespace org.w3c.dom.geolocation
{

using SharpKit.JavaScript;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields=true, OmitCasts = true)]
public partial class Position
{

	// Position
	public Coordinates coords {get;private set;}
	public long timestamp {get;private set;}
}

}