//Generated by a tool of Sebastian Loncar

namespace org.w3c.dom.geolocation
{

using SharpKit.JavaScript;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields=true, OmitCasts = true)]
public partial class PositionOptions
{

	// PositionOptions
	public bool enableHighAccuracy {get { return default(bool); } set {}}
	public int timeout {get { return default(int); } set {}}
	public int maximumAge {get { return default(int); } set {}}
}

}