//Generated by a tool of Sebastian Loncar

namespace SharpKit.Html
{

using SharpKit.JavaScript;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields = true, OmitCasts = true)]
public partial class GetSVGDocument
{

	// GetSVGDocument
	public SVGDocument sVGDocument {get; private set; }
}

}