//Generated by a tool of Sebastian Loncar

namespace SharpKit.Html
{

using SharpKit.JavaScript;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields = true, OmitCasts = true)]
public partial class SVGForeignObjectElement : SVGElement
{

	// SVGForeignObjectElement
	public SVGAnimatedLength x {get; private set; }
	public SVGAnimatedLength y {get; private set; }
	public SVGAnimatedLength width {get; private set; }
	public SVGAnimatedLength height {get; private set; }
}

}