//Generated by a tool of Sebastian Loncar

namespace SharpKit.Html
{

using SharpKit.JavaScript;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields = true, OmitCasts = true)]
public partial class HtmlMetaElement : HtmlElement
{

	// HTMLMetaElement
	public JsString name {get; set; }
	public JsString httpEquiv {get; set; }
	public JsString content {get; set; }

	// HTMLMetaElement-24
	public JsString scheme {get; set; }
}

}