//Generated by a tool of Sebastian Loncar

namespace SharpKit.Html
{

using SharpKit.JavaScript;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields = true, OmitCasts = true)]
public partial class SVGAnimatedInteger
{

	// SVGAnimatedInteger
	public int baseVal {get; set; }
	public int animVal {get; private set; }
}

}