//using SharpKit.JavaScript;
////AutoGenerated

//namespace SharpKit.Html
//{

//    public interface SQLTransactionCallback
//    {
//        // SQLTransactionCallback
//        void handleEvent(SQLTransaction transaction);
//    }

//}
