using SharpKit.JavaScript;
//AutoGenerated

namespace org.w3c.dom.css
{

    using Element = org.w3c.dom.Element;

    public interface DocumentCSS
    {
        // DocumentCSS
        CSSStyleDeclaration getOverrideStyle(Element elt, JsString pseudoElt);
    }

}
