//Generated by a tool of Sebastian Loncar

namespace org.w3c.dom.css
{

using SharpKit.JavaScript;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields=true, OmitCasts = true)]
public partial class Rect
{

	// Rect
	public CSSPrimitiveValue top {get { return default(CSSPrimitiveValue); } }
	public CSSPrimitiveValue right {get { return default(CSSPrimitiveValue); } }
	public CSSPrimitiveValue bottom {get { return default(CSSPrimitiveValue); } }
	public CSSPrimitiveValue left {get { return default(CSSPrimitiveValue); } }
}

}