//Generated by a tool of Sebastian Loncar

namespace SharpKit.Html
{

using SharpKit.JavaScript;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields = true, OmitCasts = true)]
public partial class IDBIndex
{

	// IDBIndex
	public JsString name {get; private set; }
	public JsString storeName {get; private set; }
	public JsString keyPath {get; private set; }
	public bool unique {get; private set; }
}

}