using SharpKit.JavaScript;
//AutoGenerated

namespace org.w3c.dom.ls
{

    public interface LSResourceResolver
    {
        // LSResourceResolver
        LSInput resolveResource(string type, JsString namespaceURI, JsString publicId, JsString systemId, JsString baseURI);
    }

}
