using SharpKit.JavaScript;
//AutoGenerated

namespace org.w3c.dom.views
{

    public interface ClientRect
    {
        // ClientRect
        float top {get;}
        float right {get;}
        float bottom {get;}
        float left {get;}
        float width {get;}
        float height {get;}
    }

}
