using SharpKit.JavaScript;
//AutoGenerated

namespace org.w3c.dom.ls
{

    public interface LSInput
    {
        // LSInput
        object characterStream {get;set;}
        object byteStream {get;set;}
        JsString stringData {get;set;}
        JsString systemId {get;set;}
        JsString publicId {get;set;}
        JsString baseURI {get;set;}
        JsString encoding {get;set;}
        bool certifiedText {get;set;}
    }

}
