//Generated by a tool of Sebastian Loncar

namespace SharpKit.Html
{

using SharpKit.JavaScript;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields = true, OmitCasts = true)]
public partial class HtmlOutputElement : HtmlElement
{

	// HTMLOutputElement
	public DOMSettableTokenList htmlFor {get; set; }
	public HtmlFormElement form {get; private set; }
	public JsString name {get; set; }
	public JsString type {get; private set; }
	public JsString defaultValue {get; set; }
	public JsString value {get; set; }
	public bool willValidate {get; private set; }
	public ValidityState validity {get; private set; }
	public JsString validationMessage {get; private set; }
	public bool checkValidity() { return default(bool); }
	public void setCustomValidity(string error) {}
	public NodeList labels {get; private set; }
}

}