//***************************************************
//* This file was generated by tool
//* SharpKit
//***************************************************
using SharpKit.JavaScript;
#region Ext.dd
namespace Ext.dd
{
    #region ScrollManager
    /// <summary>
    /// Provides automatic scrolling of overflow regions in the page during drag operations. The ScrollManager configs will be used as the defaults for any scroll container registered with it,
    /// but you can also override most of the configs per scroll container by adding a
    /// ddScrollConfig object to the target element that contains these properties: hthresh,
    /// vthresh, increment and frequency.  Example usage:
    /// var el = Ext.get(&#39;scroll-ct&#39;);
    /// el.ddScrollConfig = {
    /// vthresh: 50,
    /// hthresh: -1,
    /// frequency: 100,
    /// increment: 200
    /// };
    /// Ext.dd.ScrollManager.register(el);
    /// Note: This class uses &quot;Point Mode&quot; and is untested in &quot;Intersect Mode&quot;.
    /// </summary>
    [JsType(JsMode.Prototype, Export=false)]
    public partial class ScrollManager : Ext.Base
    {
        /// <summary>
        /// Manually trigger a cache refresh. ...
        /// </summary>
        public static object refreshCache(){return null;}
        /// <summary>
        /// Registers new overflow element(s) to auto scroll ...
        /// </summary>
        public static object register(object el){return null;}
        /// <summary>
        /// Unregisters overflow element(s) so they are no longer scrolled ...
        /// </summary>
        public static object unregister(object el){return null;}
        public static JsNumber animDuration{get;set;}
        public static bool animate{get;set;}
        /// <summary>
        /// The named drag drop group to which this container belongs (defaults to undefined). ...
        /// </summary>
        public static JsString ddGroup{get;set;}
        public static JsNumber frequency{get;set;}
        /// <summary>
        /// The number of pixels from the right or left edge of a container the pointer needs to be to
        /// trigger scrolling (default...
        /// </summary>
        public static JsNumber hthresh{get;set;}
        public static JsNumber increment{get;set;}
        /// <summary>
        /// The number of pixels from the top or bottom edge of a container the pointer needs to be to
        /// trigger scrolling (default...
        /// </summary>
        public static JsNumber vthresh{get;set;}
        public ScrollManager(ScrollManagerConfig config){}
        public ScrollManager(){}
    }
    #endregion
    #region ScrollManagerConfig
    [JsType(JsMode.Json, Export=false)]
    public partial class ScrollManagerConfig : Ext.BaseConfig
    {
    }
    #endregion
    #region ScrollManagerEvents
    [JsType(JsMode.Json, Export=false)]
    public partial class ScrollManagerEvents : Ext.BaseEvents
    {
    }
    #endregion
}
#endregion
