//***************************************************
//* This file was generated by tool
//* SharpKit
//***************************************************
using System;
using System.Collections.Generic;
using SharpKit.JavaScript;
namespace SharpKit.NodeJs.http
{
    /// <summary>
    /// <p>This is an <code>EventEmitter</code> with the following events:
    /// </p>
    /// </summary>
    public partial class Server
    {
        /// <summary>
        /// <p>Stops the server from accepting new connections.
        /// See <a href="net.html#server.close">net.Server.close()</a>.
        /// </p>
        /// </summary>
        public object close(){return null;}
        /// <summary>
        /// <p>Begin accepting connections on the specified port and hostname.  If the
        /// hostname is omitted, the server will accept connections directed to any
        /// IPv4 address (<code>INADDR_ANY</code>).
        /// </p>
        /// <p>To listen to a unix socket, supply a filename instead of port and hostname.
        /// </p>
        /// <p>This function is asynchronous. The last parameter <code>callback</code> will be added as
        /// a listener for the <a href="net.html#event_listening_">&apos;listening&apos;</a> event.
        /// See also <a href="net.html#server.listen">net.Server.listen()</a>.
        /// </p>
        /// </summary>
        public object listen(object port){return null;}
        /// <summary>
        /// <p>Start a UNIX socket server listening for connections on the given <code>path</code>.
        /// </p>
        /// <p>This function is asynchronous. The last parameter <code>callback</code> will be added as
        /// a listener for the <a href="net.html#event_listening_">&apos;listening&apos;</a> event.
        /// See also <a href="net.html#server.listen">net.Server.listen()</a>.
        /// </p>
        /// </summary>
        public object listen(object path, object callback){return null;}
        /// <summary>
        /// <p>Begin accepting connections on the specified port and hostname.  If the
        /// hostname is omitted, the server will accept connections directed to any
        /// IPv4 address (<code>INADDR_ANY</code>).
        /// </p>
        /// <p>To listen to a unix socket, supply a filename instead of port and hostname.
        /// </p>
        /// <p>This function is asynchronous. The last parameter <code>callback</code> will be added as
        /// a listener for the <a href="net.html#event_listening_">&apos;listening&apos;</a> event.
        /// See also <a href="net.html#server.listen">net.Server.listen()</a>.
        /// </p>
        /// </summary>
        public object listen(object port, object hostname, object callback){return null;}
    }
}
