//Generated by a tool of Sebastian Loncar

namespace SharpKit.Html
{

using SharpKit.JavaScript;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields = true, OmitCasts = true)]
public partial class IDBKeyRange
{

	// IDBKeyRange
	public static short SINGLE = 0;
	public static short LEFT_OPEN = 1;
	public static short RIGHT_OPEN = 2;
	public static short LEFT_BOUND = 4;
	public static short RIGHT_BOUND = 8;
	public object left {get; private set; }
	public object right {get; private set; }
	public short flags {get; private set; }
	public IDBKeyRange only(object value) { return default(IDBKeyRange); }
	public IDBKeyRange leftBound(object bound) { return default(IDBKeyRange); }
	public IDBKeyRange leftBound(object bound, bool open) { return default(IDBKeyRange); }
	public IDBKeyRange rightBound(object bound) { return default(IDBKeyRange); }
	public IDBKeyRange rightBound(object bound, bool open) { return default(IDBKeyRange); }
	public IDBKeyRange bound(object left, object right) { return default(IDBKeyRange); }
	public IDBKeyRange bound(object left, object right, bool openLeft) { return default(IDBKeyRange); }
	public IDBKeyRange bound(object left, object right, bool openLeft, bool openRight) { return default(IDBKeyRange); }
}

}