//***************************************************
//* This file was generated by tool
//* SharpKit
//***************************************************
using SharpKit.JavaScript;
#region Ext.chart.axis
namespace Ext.chart.axis
{
    #region Abstract
    /// <summary>
    /// Base class for all axis classes.
    /// </summary>
    [JsType(JsMode.Prototype, Export=false)]
    public partial class Abstract : Ext.Base
    {
        /// <summary>
        /// Creates new Axis. ...
        /// </summary>
        public Abstract(object config=null){}
        public Abstract(AbstractConfig config){}
    }
    #endregion
    #region AbstractConfig
    [JsType(JsMode.Json, Export=false)]
    public partial class AbstractConfig : Ext.BaseConfig
    {
    }
    #endregion
    #region AbstractEvents
    [JsType(JsMode.Json, Export=false)]
    public partial class AbstractEvents : Ext.BaseEvents
    {
    }
    #endregion
}
#endregion
