//***************************************************
//* This file was generated by tool
//* 20/07/2011 18:52:01
//* SharpKit
//***************************************************
using SharpKit.JavaScript;
#region Ext
namespace Ext
{
    #region WindowManager
    /// <summary>
    /// The default global floating Component group that is available automatically. This manages instances of floating Components which were rendered programatically without
    /// being added to a Container, and for floating Components which were added into non-floating Containers. Floating Containers create their own instance of ZIndexManager, and floating Components added at any depth below
    /// there are managed by that ZIndexManager.
    /// </summary>
    [JsType(JsMode.Prototype, Export=false)]
    public partial class WindowManager : ZIndexManager
    {
    }
    #endregion
    #region WindowManagerConfig
    [JsType(JsMode.Json, Export=false)]
    public partial class WindowManagerConfig
    {
    }
    #endregion
    #region WindowManagerEvents
    [JsType(JsMode.Json, Export=false)]
    public partial class WindowManagerEvents
    {
    }
    #endregion
}
#endregion
