//***************************************************
//* This file was generated by tool
//* 20/07/2011 20:05:54
//* SharpKit
//***************************************************
using SharpKit.JavaScript;
#region Ext.dd
namespace Ext.dd
{
    #region DDProxy
    /// <summary>
    /// A DragDrop implementation that inserts an empty, bordered div into
    /// the document that follows the cursor during drag operations.  At the time of
    /// the click, the frame div is resized to the dimensions of the linked html
    /// element, and moved to the exact location of the linked element. References to the &quot;frame&quot; element refer to the single proxy element that
    /// was created to be dragged in place of all DDProxy elements on the
    /// page.
    /// </summary>
    [JsType(JsMode.Prototype, Export=false)]
    public partial class DDProxy : DD
    {
        /// <summary>
        /// Creates new DDProxy. ...
        /// </summary>
        public DDProxy(JsString id, JsString sGroup, object config){}
        /// <summary>
        /// Creates the proxy element if it does not yet exist ...
        /// </summary>
        public object createFrame(){return null;}
        /// <summary>
        /// Initialization for the drag frame element. ...
        /// </summary>
        public object initFrame(){return null;}
        /// <summary>
        /// By default the frame is positioned exactly where the drag element is, so
        /// we use the cursor offset provided by Ext.dd.DD. ...
        /// </summary>
        public bool centerFrame{get;set;}
        /// <summary>
        /// By default we resize the drag frame to be the same size as the element
        /// we want to drag (this is to get the frame effe...
        /// </summary>
        public bool resizeFrame{get;set;}
        public DDProxy(DDProxyConfig config){}
        public DDProxy(){}
    }
    #endregion
    #region DDProxyConfig
    [JsType(JsMode.Json, Export=false)]
    public partial class DDProxyConfig : DDConfig
    {
    }
    #endregion
    #region DDProxyEvents
    [JsType(JsMode.Json, Export=false)]
    public partial class DDProxyEvents : DDEvents
    {
    }
    #endregion
}
#endregion
