//***************************************************
//* This file was generated by tool
//* 20/07/2011 18:50:44
//* SharpKit
//***************************************************
using SharpKit.JavaScript;
#region Ext.chart
namespace Ext.chart
{
    #region Callout
    /// <summary>
    /// A mixin providing callout functionality for Ext.chart.series.Series.
    /// </summary>
    [JsType(JsMode.Prototype, Export=false)]
    public partial interface Callout
    {
    }
    #endregion
    #region CalloutConfig
    [JsType(JsMode.Json, Export=false)]
    public partial class CalloutConfig
    {
    }
    #endregion
    #region CalloutEvents
    [JsType(JsMode.Json, Export=false)]
    public partial class CalloutEvents
    {
    }
    #endregion
}
#endregion
