//***************************************************
//* This file was generated by tool
//* 20/07/2011 18:50:43
//* SharpKit
//***************************************************
using SharpKit.JavaScript;
#region Ext.chart.axis
namespace Ext.chart.axis
{
    #region Abstract
    /// <summary>
    /// Base class for all axis classes.
    /// </summary>
    [JsType(JsMode.Prototype, Export=false)]
    public partial class Abstract : Ext.Base
    {
        /// <summary>
        /// Creates new Axis. ...
        /// </summary>
        public object constructor(object config=null){return null;}
    }
    #endregion
    #region AbstractConfig
    [JsType(JsMode.Json, Export=false)]
    public partial class AbstractConfig
    {
    }
    #endregion
    #region AbstractEvents
    [JsType(JsMode.Json, Export=false)]
    public partial class AbstractEvents
    {
    }
    #endregion
}
#endregion
