//***************************************************
//* This file was generated by tool
//* 20/07/2011 20:05:54
//* SharpKit
//***************************************************
using SharpKit.JavaScript;
#region Ext.data
namespace Ext.data
{
    #region ResultSet
    /// <summary>
    /// Simple wrapper class that represents a set of records returned by a Proxy.
    /// </summary>
    [JsType(JsMode.Prototype, Export=false)]
    public partial class ResultSet
    {
        /// <summary>
        /// Creates the resultSet ...
        /// </summary>
        public ResultSet(object config=null){}
        /// <summary>
        /// DEPRECATED - will be removed in Ext JS 5.0. ...
        /// </summary>
        public object totalRecords{get;set;}
        public ResultSet(ResultSetConfig config){}
    }
    #endregion
    #region ResultSetConfig
    [JsType(JsMode.Json, Export=false)]
    public partial class ResultSetConfig
    {
        /// <summary>
        /// The number of records in this ResultSet. ...
        /// </summary>
        public JsNumber count{get;set;}
        /// <summary>
        /// True if the records have already been loaded. ...
        /// </summary>
        public bool loaded{get;set;}
        /// <summary>
        /// The array of record instances. ...
        /// </summary>
        public JsArray records{get;set;}
        public bool success{get;set;}
        /// <summary>
        /// The total number of records reported by the data source. ...
        /// </summary>
        public JsNumber total{get;set;}
    }
    #endregion
    #region ResultSetEvents
    [JsType(JsMode.Json, Export=false)]
    public partial class ResultSetEvents
    {
    }
    #endregion
}
#endregion
