//***************************************************
//* This file was generated by tool
//* 20/07/2011 19:12:24
//* SharpKit
//***************************************************
using SharpKit.JavaScript;
#region Ext.direct
namespace Ext.direct
{
    #region JsonProvider
    /// <summary>
    /// A base provider for communicating using JSON. This is an abstract class
    /// and should not be instanced directly.
    /// </summary>
    [JsType(JsMode.Prototype, Export=false)]
    public partial class JsonProvider : Ext.direct.Provider, Ext.util.Observable
    {
        /// <summary>
        /// Create an event from a response object ...
        /// </summary>
        public Ext.direct.Event createEvent(object response){return null;}
    }
    #endregion
    #region JsonProviderConfig
    [JsType(JsMode.Json, Export=false)]
    public partial class JsonProviderConfig : Ext.direct.ProviderConfig
    {
    }
    #endregion
    #region JsonProviderEvents
    [JsType(JsMode.Json, Export=false)]
    public partial class JsonProviderEvents : Ext.direct.ProviderEvents
    {
    }
    #endregion
}
#endregion
