//***************************************************
//* This file was generated by tool
//* 20/07/2011 20:05:54
//* SharpKit
//***************************************************
using SharpKit.JavaScript;
#region Ext.dd
namespace Ext.dd
{
    #region DDTarget
    /// <summary>
    /// A DragDrop implementation that does not move, but can be a drop
    /// target.  You would get the same result by simply omitting implementation
    /// for the event callbacks, but this way we reduce the processing cost of the
    /// event listener and the callbacks.
    /// </summary>
    [JsType(JsMode.Prototype, Export=false)]
    public partial class DDTarget : Ext.dd.DragDrop
    {
        /// <summary>
        /// Creates new DDTarget. ...
        /// </summary>
        public DDTarget(JsString id, JsString sGroup, object config){}
        public DDTarget(DDTargetConfig config){}
        public DDTarget(){}
    }
    #endregion
    #region DDTargetConfig
    [JsType(JsMode.Json, Export=false)]
    public partial class DDTargetConfig : Ext.dd.DragDropConfig
    {
    }
    #endregion
    #region DDTargetEvents
    [JsType(JsMode.Json, Export=false)]
    public partial class DDTargetEvents : Ext.dd.DragDropEvents
    {
    }
    #endregion
}
#endregion
