/*@Generated by SharpKit v4.22.7000*/
MyStringEnum = {ValueA:"ValueA",ValueB:"ValueB"};
MyIntEnum = {ValueA:0,ValueB:1};
function btn_onclick()
{
    alert("MyStringEnum.ValueA:" + MyStringEnum.ValueA + " MyIntEnum.ValueA:" + MyIntEnum.ValueA);
}
