//***************************************************
//* This file was generated by tool
//* SharpKit
//***************************************************
using SharpKit.JavaScript;
#region Ext.slider
namespace Ext.slider
{
    #region Single
    /// <summary>
    /// Slider which supports vertical or horizontal orientation, keyboard adjustments,
    /// configurable snapping, axis clicking and animation. Can be added as an item to
    /// any container.
    /// Example usage:     Ext.create(&#39;Ext.slider.Single&#39;, {
    /// width: 200,
    /// value: 50,
    /// increment: 10,
    /// minValue: 0,
    /// maxValue: 100,
    /// renderTo: Ext.getBody()
    /// });
    /// The class Ext.slider.Single is aliased to Ext.Slider for backwards compatibility.
    /// </summary>
    [JsType(JsMode.Prototype, Export=false)]
    public partial class Single : Multi, Ext.form.Labelable, Ext.form.field.Field, Ext.util.Floating, Ext.util.Observable, Ext.util.Animate, Ext.state.Stateful
    {
        /// <summary>
        /// Returns the current value of the slider ...
        /// </summary>
        public new JsNumber getValue(){return null;}
        /// <summary>
        /// Programmatically sets the value of the Slider. ...
        /// </summary>
        public object setValue(JsNumber value, bool animate){return null;}
        public Single(SingleConfig config){}
        public Single(){}
    }
    #endregion
    #region SingleConfig
    [JsType(JsMode.Json, Export=false)]
    public partial class SingleConfig : MultiConfig
    {
    }
    #endregion
    #region SingleEvents
    [JsType(JsMode.Json, Export=false)]
    public partial class SingleEvents : MultiEvents
    {
    }
    #endregion
}
#endregion
