//***************************************************
//* This file was generated by tool
//* SharpKit
//***************************************************
using SharpKit.JavaScript;
#region Ext.chart
namespace Ext.chart
{
    #region TipSurface
    /// <inheritdocs />
    /// <summary>
    /// <p><strong>NOTE</strong> This is a private utility class for internal use by the framework. Don't rely on its existence.</p>
    /// </summary>
    [JsType(JsMode.Prototype, Export=false, OmitOptionalParameters=true)]
    public partial class TipSurface : Ext.draw.Component
    {
        public TipSurface(TipSurfaceConfig config){}
        public TipSurface(){}
        public TipSurface(params object[] args){}
    }
    #endregion
    #region TipSurfaceConfig
    /// <inheritdocs />
    [JsType(JsMode.Json, Export=false, OmitOptionalParameters=true)]
    public partial class TipSurfaceConfig : Ext.draw.ComponentConfig
    {
        public TipSurfaceConfig(params object[] args){}
    }
    #endregion
    #region TipSurfaceEvents
    /// <inheritdocs />
    [JsType(JsMode.Json, Export=false, OmitOptionalParameters=true)]
    public partial class TipSurfaceEvents : Ext.draw.ComponentEvents
    {
        public TipSurfaceEvents(params object[] args){}
    }
    #endregion
}
#endregion
