/*Generated by SharpKit 5 v4.29.7000*/
$(OnReady);
function OnReady()
{
    $("#panelbar").kendoPanelBar({expandMode:"single",select:onSelect,expand:onExpand,collapse:onCollapse,activate:onActivate,contentLoad:onContentLoad,error:onError,contentUrls: ["","","","../../content/web/panelbar/ajax/ajaxContent1.html","error.html"]}).css({width:"250px"}).css({margin:"20px auto"});
};
function onSelect(e)
{
    kendoConsole.log("Select: " + $(e.item).find("> .k-link").text());
};
function onExpand(e)
{
    kendoConsole.log("Expand: " + $(e.item).find("> .k-link").text());
};
function onCollapse(e)
{
    kendoConsole.log("Collapse: " + $(e.item).find("> .k-link").text());
};
function onActivate(e)
{
    kendoConsole.log("Activate: " + $(e.item).find("> .k-link").text());
};
function onContentLoad(e)
{
    kendoConsole.log("Content loaded in <b>" + $(e.item).find("> .k-link").text() + "</b> and starts with <b>" + $(e.contentElement).text().substr(0,20) + "...</b>");
};
function onError(e)
{
    kendoConsole.error("Loading failed with " + e.xhr.statusText + " " + e.xhr.status);
};
