//Generated by a tool of Sebastian Loncar

namespace SharpKit.Html
{

using SharpKit.JavaScript;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields = true, OmitCasts = true)]
public partial class DOMErrorHandler
{

	// DOMErrorHandler
	public bool handleError(DOMError error) { return default(bool); }
}

}