/*Generated by SharpKit 5 v4.28.5000*/
function DefaultClient_Load()
{
    $(document.body).append("Ready<br/>");
    $(document.body).append("Ready world2<br/>");
    $(document.body).append("Ready world3<br/>");
    $(document.body).append("Ready world4<br/>");
    $(document.body).append("Ready world5<br/>");
};
function btnTest_click(e)
{
    $(document.body).append("Hello world<br/>");
    $(document.body).append("Hello world2<br/>");
    $(document.body).append("Hello world3<br/>");
    $(document.body).append("Hello world4<br/>");
    $(document.body).append("Hello world5<br/>");
};
//@ sourceMappingURL=Default.map.js