//Generated by a tool of Sebastian Loncar

namespace org.w3c.dom.webdatabase
{

using SharpKit.JavaScript;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields=true, OmitCasts = true)]
public partial class SQLResultSetRowList
{

	// SQLResultSetRowList
	public int length {get;private set;}
	[JsProperty(NativeIndexer = true)]
	public object this[int index] {get{return null;}}
}

}