//Generated by a tool of Sebastian Loncar

namespace org.w3c.dom.webdatabase
{

using SharpKit.JavaScript;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields=true, OmitCasts = true)]
public partial class SQLResultSet
{

	// SQLResultSet
	public int insertId {get { return default(int); } }
	public int rowsAffected {get { return default(int); } }
	public SQLResultSetRowList rows {get { return default(SQLResultSetRowList); } }
}

}