//Generated by a tool of Sebastian Loncar

namespace org.w3c.dom.html
{

using SharpKit.JavaScript;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields=true, OmitCasts = true)]
public partial class ApplicationCache
{

	// ApplicationCache
	public static short UNCACHED = 0;
	public static short IDLE = 1;
	public static short CHECKING = 2;
	public static short DOWNLOADING = 3;
	public static short UPDATEREADY = 4;
	public static short OBSOLETE = 5;
	public short status {get;private set;}
	public void update() {}
	public void swapCache() {}
	public JsAction onchecking {get;set;}
	public JsAction onerror {get;set;}
	public JsAction onnoupdate {get;set;}
	public JsAction ondownloading {get;set;}
	public JsAction onprogress {get;set;}
	public JsAction onupdateready {get;set;}
	public JsAction oncached {get;set;}
	public JsAction onobsolete {get;set;}
}

}