//AutoGenerated

namespace org.w3c.dom.html
{

    using Event = org.w3c.dom.events.Event;

    public interface BeforeUnloadEvent : org.w3c.dom.events.Event
    {
        // BeforeUnloadEvent
        string returnValue {get;set;}
    }

}