//AutoGenerated

namespace org.w3c.dom.html
{

    public interface HTMLTableElement : HTMLElement
    {
        // HTMLTableElement
        HTMLTableCaptionElement caption {get;set;}
        HTMLElement createCaption();
        void deleteCaption();
        HTMLTableSectionElement tHead {get;set;}
        HTMLElement createTHead();
        void deleteTHead();
        HTMLTableSectionElement tFoot {get;set;}
        HTMLElement createTFoot();
        void deleteTFoot();
        HTMLCollection tBodies {get;}
        HTMLElement createTBody();
        HTMLCollection rows {get;}
        HTMLElement insertRow();
        HTMLElement insertRow(int index);
        void deleteRow(int index);
        string summary {get;set;}
        // HTMLTableElement-31
        string align {get;set;}
        string bgColor {get;set;}
        string border {get;set;}
        string cellPadding {get;set;}
        string cellSpacing {get;set;}
        string frame {get;set;}
        string rules {get;set;}
        string width {get;set;}
    }

}