using SharpKit.JavaScript;
//AutoGenerated

namespace org.w3c.dom.html
{

    public interface HTMLLabelElement : HTMLElement
    {
        // HTMLLabelElement
        HTMLFormElement form {get;}
        JsString htmlFor {get;set;}
        HTMLElement control {get;}
    }

}
