//Generated by a tool of Sebastian Loncar

namespace org.w3c.dom.html
{

using SharpKit.JavaScript;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields=true, OmitCasts = true)]
public partial class HTMLAppletElement : HTMLElement
{

	// HTMLAppletElement
	public string align {get;set;}
	public string alt {get;set;}
	public string archive {get;set;}
	public string code {get;set;}
	public string codeBase {get;set;}
	public string height {get;set;}
	public int hspace {get;set;}
	public string name {get;set;}
	public string @object {get;set;}
	public int vspace {get;set;}
	public string width {get;set;}
}

}