//AutoGenerated

namespace org.w3c.dom.html
{

    public interface HTMLTableCaptionElement : HTMLElement
    {
        // HTMLTableCaptionElement
        // HTMLTableCaptionElement-8
        string align {get;set;}
    }

}