//Generated by a tool of Sebastian Loncar

namespace org.w3c.dom.html
{

using SharpKit.JavaScript;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields=true, OmitCasts = true)]
public partial class HTMLCanvasElement : HTMLElement
{

	// HTMLCanvasElement
	public int width {get;set;}
	public int height {get;set;}
	public string toDataURL() { return default(string); }
	public string toDataURL(string type, params object[] args) { return default(string); }
	public object getContext(string contextId) { return default(object); }
}

}