using SharpKit.JavaScript;
//AutoGenerated

namespace org.w3c.dom.html
{

    public interface HTMLTableRowElement : HTMLElement
    {
        // HTMLTableRowElement
        int rowIndex {get;}
        int sectionRowIndex {get;}
        HTMLCollection cells {get;}
        HTMLElement insertCell();
        HTMLElement insertCell(int index);
        void deleteCell(int index);
        // HTMLTableRowElement-34
        JsString align {get;set;}
        JsString bgColor {get;set;}
        JsString ch {get;set;}
        JsString chOff {get;set;}
        JsString vAlign {get;set;}
    }

}
