//Generated by a tool of Sebastian Loncar

namespace org.w3c.dom.html
{

using SharpKit.JavaScript;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields=true, OmitCasts = true)]
public partial class HTMLCommandElement : HTMLElement
{

	// HTMLCommandElement
	public string type {get;set;}
	public string label {get;set;}
	public string icon {get;set;}
	public bool disabled {get;set;}
	public bool @checked {get;set;}
	public string radiogroup {get;set;}
}

}