//Generated by a tool of Sebastian Loncar

namespace org.w3c.dom.html
{

using SharpKit.JavaScript;
using NodeList = org.w3c.dom.NodeList;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields=true, OmitCasts = true)]
public partial class HTMLTextAreaElement : HTMLElement
{

	// HTMLTextAreaElement
	public bool autofocus {get;set;}
	public int cols {get;set;}
	public bool disabled {get;set;}
	public HTMLFormElement form {get;private set;}
	public int maxLength {get;set;}
	public string name {get;set;}
	public string placeholder {get;set;}
	public bool readOnly {get;set;}
	public bool required {get;set;}
	public int rows {get;set;}
	public string wrap {get;set;}
	public string type {get;private set;}
	public string defaultValue {get;set;}
	public string value {get;set;}
	public int textLength {get;private set;}
	public bool willValidate {get;private set;}
	public ValidityState validity {get;private set;}
	public string validationMessage {get;private set;}
	public bool checkValidity() { return default(bool); }
	public void setCustomValidity(string error) {}
	public NodeList labels {get;private set;}
	public void select() {}
	public int selectionStart {get;set;}
	public int selectionEnd {get;set;}
	public void setSelectionRange(int start, int end) {}
}

}