//Generated by a tool of Sebastian Loncar

namespace org.w3c.dom.html
{

using SharpKit.JavaScript;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields=true, OmitCasts = true)]
public partial class HTMLBaseElement : HTMLElement
{

	// HTMLBaseElement
	public string href {get { return default(string); } set {}}
	public string target {get { return default(string); } set {}}
}

}