//Generated by a tool of Sebastian Loncar

namespace org.w3c.dom.html
{

using SharpKit.JavaScript;
using NodeList = org.w3c.dom.NodeList;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields=true, OmitCasts = true)]
public partial class HTMLOutputElement : HTMLElement
{

	// HTMLOutputElement
	public DOMSettableTokenList htmlFor {get;set;}
	public HTMLFormElement form {get;private set;}
	public string name {get;set;}
	public string type {get;private set;}
	public string defaultValue {get;set;}
	public string value {get;set;}
	public bool willValidate {get;private set;}
	public ValidityState validity {get;private set;}
	public string validationMessage {get;private set;}
	public bool checkValidity() { return default(bool); }
	public void setCustomValidity(string error) {}
	public NodeList labels {get;private set;}
}

}