//Generated by a tool of Sebastian Loncar

namespace org.w3c.dom.html
{

using SharpKit.JavaScript;
using NodeList = org.w3c.dom.NodeList;
using File = org.w3c.dom.file.File;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields=true, OmitCasts = true)]
public partial class HTMLInputElement : HTMLElement
{

	// HTMLInputElement
	public string accept {get;set;}
	public string alt {get;set;}
	public bool autocomplete {get;set;}
	public bool autofocus {get;set;}
	public bool defaultChecked {get;set;}
	public bool @checked {get;set;}
	public bool disabled {get;set;}
	public HTMLFormElement form {get;private set;}
	public File files {get;private set;}
	public string formAction {get;set;}
	public string formEnctype {get;set;}
	public string formMethod {get;set;}
	public bool formNoValidate {get;set;}
	public string formTarget {get;set;}
	public string height {get;set;}
	public bool indeterminate {get;set;}
	public HTMLElement list {get;private set;}
	public string max {get;set;}
	public int maxLength {get;set;}
	public string min {get;set;}
	public bool multiple {get;set;}
	public string name {get;set;}
	public string pattern {get;set;}
	public string placeholder {get;set;}
	public bool readOnly {get;set;}
	public bool required {get;set;}
	public int size {get;set;}
	public string src {get;set;}
	public string step {get;set;}
	public string type {get;set;}
	public string defaultValue {get;set;}
	public string value {get;set;}
	public long valueAsDate {get;set;}
	public float valueAsNumber {get;set;}
	public HTMLOptionElement selectedOption {get;private set;}
	public string width {get;set;}
	public void stepUp() {}
	public void stepUp(int n) {}
	public void stepDown() {}
	public void stepDown(int n) {}
	public bool willValidate {get;private set;}
	public ValidityState validity {get;private set;}
	public string validationMessage {get;private set;}
	public bool checkValidity() { return default(bool); }
	public void setCustomValidity(string error) {}
	public NodeList labels {get;private set;}
	public void select() {}
	public int selectionStart {get;set;}
	public int selectionEnd {get;set;}
	public void setSelectionRange(int start, int end) {}

	// HTMLInputElement-19
	public string align {get;set;}
	public string useMap {get;set;}
}

}