using SharpKit.JavaScript;
//AutoGenerated

namespace org.w3c.dom.html
{

    using Element = org.w3c.dom.Element;
    using NodeList = org.w3c.dom.NodeList;

    public partial interface HTMLDocument
    {
        // HTMLDocument
        Location location {get;set;}
        JsString uRL {get;}
        JsString domain {get;set;}
        JsString referrer {get;}
        JsString cookie {get;set;}
        JsString lastModified {get;}
        JsString compatMode {get;}
        JsString charset {get;set;}
        JsString characterSet {get;}
        JsString defaultCharset {get;}
        JsString readyState {get;}
        object getElement(string name);
        JsString title {get;set;}
        JsString dir {get;set;}
        HTMLElement body {get;set;}
        HTMLHeadElement head {get;}
        HTMLCollection images {get;}
        HTMLCollection embeds {get;}
        HTMLCollection plugins {get;}
        HTMLCollection links {get;}
        HTMLCollection forms {get;}
        HTMLCollection scripts {get;}
        NodeList getElementsByName(string elementName);
        NodeList getElementsByClassName(string classNames);
        JsString innerHTML {get;set;}
        HTMLDocument open();
        HTMLDocument open(string type);
        HTMLDocument open(string type, JsString replace);
        Window open(string url, JsString name, JsString features);
        Window open(string url, JsString name, JsString features, bool replace);
        void close();
        void write(params JsString[] text);
        void writeln(params JsString[] text);
        Selection selection {get;}
        Element activeElement {get;}
        bool hasFocus();
        JsString designMode {get;set;}
        bool execCommand(string commandId);
        bool execCommand(string commandId, bool showUI);
        bool execCommand(string commandId, bool showUI, JsString value);
        bool queryCommandEnabled(string commandId);
        bool queryCommandIndeterm(string commandId);
        bool queryCommandState(string commandId);
        bool queryCommandSupported(string commandId);
        JsString queryCommandValue(string commandId);
        HTMLCollection commands {get;}
        Function onabort {get;set;}
        Function onblur {get;set;}
        Function oncanplay {get;set;}
        Function oncanplaythrough {get;set;}
        Function onchange {get;set;}
        Function onclick {get;set;}
        Function oncontextmenu {get;set;}
        Function ondblclick {get;set;}
        Function ondrag {get;set;}
        Function ondragend {get;set;}
        Function ondragenter {get;set;}
        Function ondragleave {get;set;}
        Function ondragover {get;set;}
        Function ondragstart {get;set;}
        Function ondrop {get;set;}
        Function ondurationchange {get;set;}
        Function onemptied {get;set;}
        Function onended {get;set;}
        Function onerror {get;set;}
        Function onfocus {get;set;}
        Function onformchange {get;set;}
        Function onforminput {get;set;}
        Function oninput {get;set;}
        Function oninvalid {get;set;}
        Function onkeydown {get;set;}
        Function onkeypress {get;set;}
        Function onkeyup {get;set;}
        Function onload {get;set;}
        Function onloadeddata {get;set;}
        Function onloadedmetadata {get;set;}
        Function onloadstart {get;set;}
        Function onmousedown {get;set;}
        Function onmousemove {get;set;}
        Function onmouseout {get;set;}
        Function onmouseover {get;set;}
        Function onmouseup {get;set;}
        Function onmousewheel {get;set;}
        Function onpause {get;set;}
        Function onplay {get;set;}
        Function onplaying {get;set;}
        Function onprogress {get;set;}
        Function onratechange {get;set;}
        Function onreadystatechange {get;set;}
        Function onscroll {get;set;}
        Function onseeked {get;set;}
        Function onseeking {get;set;}
        Function onselect {get;set;}
        Function onshow {get;set;}
        Function onstalled {get;set;}
        Function onsubmit {get;set;}
        Function onsuspend {get;set;}
        Function ontimeupdate {get;set;}
        Function onvolumechange {get;set;}
        Function onwaiting {get;set;}
        // HTMLDocument-36
        JsString fgColor {get;set;}
        JsString bgColor {get;set;}
        JsString linkColor {get;set;}
        JsString vlinkColor {get;set;}
        JsString alinkColor {get;set;}
        HTMLCollection anchors {get;}
        HTMLCollection applets {get;}
        void clear();
        HTMLAllCollection all {get;}
        // HTMLDocument-37
        NodeList items {get;}
        NodeList getItems(string typeNames);
    }

}
