using SharpKit.JavaScript;
//AutoGenerated

namespace org.w3c.dom.html
{

    using Event = org.w3c.dom.events.Event;

    public interface MessageEvent : org.w3c.dom.events.Event
    {
        // MessageEvent
        object data {get;}
        JsString origin {get;}
        JsString lastEventId {get;}
        Window source {get;}
        MessagePort[] ports {get;}
        void initMessageEvent(string typeArg, bool canBubbleArg, bool cancelableArg, object dataArg, JsString originArg, JsString lastEventIdArg, Window sourceArg, MessagePort[] portsArg);
    }

}
