//Generated by a tool of Sebastian Loncar

namespace org.w3c.dom.html
{

using SharpKit.JavaScript;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields=true, OmitCasts = true)]
public partial class UndoManager
{

	// UndoManager
	public int length {get { return default(int); } }
	[JsProperty(NativeIndexer = true)]
	public object this[int index] {get { return default(object); } }
	public int position {get { return default(int); } }
	public int add(object data, string title) { return default(int); }
	public void remove(int index) {}
	public void clearUndo() {}
	public void clearRedo() {}
}

}