//Generated by a tool of Sebastian Loncar

namespace SharpKit.Html
{

using SharpKit.JavaScript;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields = true, OmitCasts = true)]
public partial class DocumentFragment : Node
{

	// DocumentFragment

	// NodeSelector
	public Element querySelector(string selectors) { return default(Element); }
	public NodeList querySelectorAll(string selectors) { return default(NodeList); }
}

}