//Generated by a tool of Sebastian Loncar

namespace SharpKit.Html
{

using SharpKit.JavaScript;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields = true, OmitCasts = true)]
public partial class SVGAnimationElement : SVGElement
{

	// SVGAnimationElement
	public SVGElement targetElement {get; private set; }
	public float startTime {get; private set; }
	public float currentTime {get; private set; }
	public float simpleDuration {get; private set; }
}

}