using SharpKit.JavaScript;
//AutoGenerated

namespace org.w3c.dom
{

    public interface DOMStringList
    {
        // DOMStringList
        JsString item(int index);
        int length {get;}
        bool contains(string str);
    }

}
