//Generated by a tool of Sebastian Loncar

namespace org.w3c.dom
{

using SharpKit.JavaScript;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields=true, OmitCasts = true)]
public partial class FloatArray
{

	// FloatArray
	public int length {get;set;}
	public float getElement(int index) { return default(float); }
	public void setElement(int index, float value) {}
}

}