using SharpKit.JavaScript;
//AutoGenerated

namespace org.w3c.dom
{

    public interface LongLongArray
    {
        // LongLongArray
        int length {get;set;}
        long getElement(int index);
        void setElement(int index, long value);
    }

}
