using SharpKit.JavaScript;
//AutoGenerated

namespace org.w3c.dom
{

    public interface ProcessingInstruction : Node
    {
        // ProcessingInstruction
        JsString target {get;}
        JsString data {get;set;}
//TODO:
//ORIGINAL LINE: public void setData(String data) throws DOMException;
    }

}
