//Generated by a tool of Sebastian Loncar

namespace org.w3c.dom
{

using SharpKit.JavaScript;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields=true, OmitCasts = true)]
public partial class UnsignedShortArray
{

	// UnsignedShortArray
	public int length {get;set;}
	public short getElement(int index) { return default(short); }
	public void setElement(int index, short value) {}
}

}