//Generated by a tool of Sebastian Loncar

namespace org.w3c.dom
{

using SharpKit.JavaScript;
using EventTarget = org.w3c.dom.events.EventTarget;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields=true, OmitCasts = true)]
public partial class XMLHttpRequestEventTarget : EventTarget
{

	// XMLHttpRequestEventTarget
	public JsAction onloadstart {get;set;}
	public JsAction onprogress {get;set;}
	public JsAction onabort {get;set;}
	public JsAction onerror {get;set;}
	public JsAction onload {get;set;}
	public JsAction ontimeout {get;set;}
	public JsAction onloadend {get;set;}
}

}