//Generated by a tool of Sebastian Loncar

namespace SharpKit.Html
{

using SharpKit.JavaScript;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields = true, OmitCasts = true)]
public partial class StyleSheet
{

	// StyleSheet
	public JsString type {get; private set; }
	public JsString href {get; private set; }
	public Node ownerNode {get; private set; }
	public StyleSheet parentStyleSheet {get; private set; }
	public JsString title {get; private set; }
	public MediaList media {get; set; }
	public bool disabled {get; set; }
}

}