// Generated by SharpKit.QooxDoo.Generator
using System;
using System.Collections.Generic;
using SharpKit.Html;
using SharpKit.JavaScript;

namespace qx.ui.tree
{
    /// <summary>
	/// <para>The tree item is a tree element for the <see cref="VirtualTree"/>, which can have
	/// nested tree elements.</para>
	/// </summary>
	[JsType(JsMode.Prototype, Name = "qx.ui.tree.VirtualTreeItem", OmitOptionalParameters = true, Export = false)]
    public partial class VirtualTreeItem : qx.ui.tree.core.AbstractItem
    {
		#region Properties

		[JsProperty(Name = "appearance", NativeField = true)]
		public object Appearance { get; set; }

		#endregion Properties

		#region Methods

		public VirtualTreeItem() { throw new NotImplementedException(); }

		[JsMethod(Name = "getLevel")]
		public void GetLevel() { throw new NotImplementedException(); }

		[JsMethod(Name = "hasChildren")]
		public void HasChildren() { throw new NotImplementedException(); }

		#endregion Methods
    }
}