//Generated by a tool of Sebastian Loncar

namespace org.w3c.dom.smil
{

using SharpKit.JavaScript;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields=true, OmitCasts = true)]
public partial class ElementTimeControl
{

	// ElementTimeControl
	public void beginElement() {}
	public void beginElementAt(float offset) {}
	public void endElement() {}
	public void endElementAt(float offset) {}
}

}