/*Generated by SharpKit 5 v4.30.1000*/
$(OnReady);
function OnReady()
{
    $("#draggable").draggable();
    $("#droppable, #droppable-inner").droppable(
    {
        activeClass: "ui-state-hover",
        hoverClass: "ui-state-active",
        drop: function (e, ui)
        {
            $(e.currentTarget).addClass("ui-state-highlight").find("> p").html("Dropped!");
            return false;
        }
    });
    $("#droppable2, #droppable2-inner").droppable(
    {
        greedy: true,
        activeClass: "ui-state-hover",
        hoverClass: "ui-state-active",
        drop: function (e, ui)
        {
            $(e.currentTarget).addClass("ui-state-highlight").find(" > p ").html("Dropped!");
        }
    });
};
