/*Generated by SharpKit 5 v4.30.0000*/
if (typeof(JsTypes) == "undefined")
    var JsTypes = [];
var CoreTests$Methods$DelegateTest =
{
    fullname: "CoreTests.Methods.DelegateTest",
    baseTypeName: "System.Object",
    assemblyName: "CoreTests",
    Kind: "Class",
    definition:
    {
        ctor: function ()
        {
            System.Object.ctor.call(this);
        },
        main: function ()
        {
            this.func1$$JsAction(null);
            this.func1$$JsAction(null);
            this.func2$$JsAction(null);
            this.func2$$JsAction(null);
            this.func3$$Action(null);
            this.func3$$Action$1$String(null);
            this.func4$$Action$1$String(null);
            this.func4$$Action$1$Int32(null);
        },
        func1$$JsAction: function (callback)
        {
        },
        func2$$JsAction: function (callback)
        {
        },
        func3$$Action: function (callback)
        {
        },
        func3$$Action$1$String: function (callback)
        {
        },
        func4$$Action$1$String: function (callback)
        {
        },
        func4$$Action$1$Int32: function (callback)
        {
        }
    }
};
JsTypes.push(CoreTests$Methods$DelegateTest);
