using SharpKit.JavaScript;
//AutoGenerated

namespace org.w3c.dom.html
{

    public interface DOMStringMap
    {
        // DOMStringMap
        JsString getElement(string name);
        void setElement(string name, JsString value);
        void createElement(string name, JsString value);
        void deleteElement(string name);
    }

}
