//Generated by a tool of Sebastian Loncar

namespace org.w3c.dom.html
{

using SharpKit.JavaScript;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields=true, OmitCasts = true)]
public partial class HTMLAreaElement : HTMLElement
{

	// HTMLAreaElement
	public string alt {get { return default(string); } set {}}
	public string coords {get { return default(string); } set {}}
	public string shape {get { return default(string); } set {}}
	public string href {get { return default(string); } set {}}
	public string target {get { return default(string); } set {}}
	public string ping {get { return default(string); } set {}}
	public string rel {get { return default(string); } set {}}
	public DOMTokenList relList {get { return default(DOMTokenList); } }
	public string media {get { return default(string); } set {}}
	public string hreflang {get { return default(string); } set {}}
	public string type {get { return default(string); } set {}}
	public string protocol {get { return default(string); } set {}}
	public string host {get { return default(string); } set {}}
	public string hostname {get { return default(string); } set {}}
	public string port {get { return default(string); } set {}}
	public string pathname {get { return default(string); } set {}}
	public string search {get { return default(string); } set {}}
	public string hash {get { return default(string); } set {}}

	// HTMLAreaElement-5
	public bool noHref {get { return default(bool); } set {}}
}

}