//Generated by a tool of Sebastian Loncar

namespace org.w3c.dom.html
{

using SharpKit.JavaScript;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields=true, OmitCasts = true)]
public partial class HTMLTableColElement : HTMLElement
{

	// HTMLTableColElement
	public int span {get { return default(int); } set {}}

	// HTMLTableColElement-9
	public string align {get { return default(string); } set {}}
	public string ch {get { return default(string); } set {}}
	public string chOff {get { return default(string); } set {}}
	public string vAlign {get { return default(string); } set {}}
	public string width {get { return default(string); } set {}}
}

}