//Generated by a tool of Sebastian Loncar

namespace org.w3c.dom.html
{

using SharpKit.JavaScript;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields=true, OmitCasts = true)]
public partial class HTMLDivElement : HTMLElement
{

	// HTMLDivElement

	// HTMLDivElement-10
	public string align {get;set;}
}

}