//AutoGenerated

namespace org.w3c.dom.html
{

    public interface HTMLBRElement : HTMLElement
    {
        // HTMLBRElement
        // HTMLBRElement-7
        string clear {get;set;}
    }

}