//AutoGenerated

namespace org.w3c.dom.html
{

    public interface HTMLLinkElement : HTMLElement
    {
        // HTMLLinkElement
        bool disabled {get;set;}
        string href {get;set;}
        string rel {get;set;}
        DOMTokenList relList {get;}
        string media {get;set;}
        string hreflang {get;set;}
        string type {get;set;}
        DOMSettableTokenList sizes {get;set;}
        // HTMLLinkElement-22
        string charset {get;set;}
        string rev {get;set;}
        string target {get;set;}
    }

}