using SharpKit.JavaScript;
//AutoGenerated

namespace org.w3c.dom.html
{

    public interface HTMLQuoteElement : HTMLElement
    {
        // HTMLQuoteElement
        JsString cite {get;set;}
    }

}
