//Generated by a tool of Sebastian Loncar

namespace org.w3c.dom.html
{

using SharpKit.JavaScript;
using DOMStringList = org.w3c.dom.DOMStringList;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields=true, OmitCasts = true)]
public partial class HTMLPropertiesCollection : HTMLCollection
{

	// HTMLPropertiesCollection
	[JsProperty(NativeIndexer = true)]
	public PropertyNodeList this[string name] {get{return null;}}
	public DOMStringList names {get;private set;}
}

}