using SharpKit.JavaScript;
//AutoGenerated

namespace org.w3c.dom.html
{

    public interface HTMLOptGroupElement : HTMLElement
    {
        // HTMLOptGroupElement
        bool disabled {get;set;}
        JsString label {get;set;}
    }

}
