using SharpKit.JavaScript;
//AutoGenerated

namespace org.w3c.dom.html
{

    public interface HTMLBodyElement : HTMLElement
    {
        // HTMLBodyElement
        Function onafterprint {get;set;}
        Function onbeforeprint {get;set;}
        Function onbeforeunload {get;set;}
        Function onblur {get;set;}
        Function onerror {get;set;}
        Function onfocus {get;set;}
        Function onhashchange {get;set;}
        Function onload {get;set;}
        Function onmessage {get;set;}
        Function onoffline {get;set;}
        Function ononline {get;set;}
        Function onpopstate {get;set;}
        Function onpagehide {get;set;}
        Function onpageshow {get;set;}
        Function onredo {get;set;}
        Function onresize {get;set;}
        Function onstorage {get;set;}
        Function onundo {get;set;}
        Function onunload {get;set;}
        // HTMLBodyElement-6
        JsString text {get;set;}
        JsString bgColor {get;set;}
        JsString background {get;set;}
        JsString link {get;set;}
        JsString vLink {get;set;}
        JsString aLink {get;set;}
    }

}
