//Generated by a tool of Sebastian Loncar

namespace org.w3c.dom.html
{

using SharpKit.JavaScript;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields=true, OmitCasts = true)]
public partial class HTMLCommandElement : HTMLElement
{

	// HTMLCommandElement
	public string type {get { return default(string); } set {}}
	public string label {get { return default(string); } set {}}
	public string icon {get { return default(string); } set {}}
	public bool disabled {get { return default(bool); } set {}}
	public bool @checked {get { return default(bool); } set {}}
	public string radiogroup {get { return default(string); } set {}}
}

}