//Generated by a tool of Sebastian Loncar

namespace org.w3c.dom.html
{

using SharpKit.JavaScript;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields=true, OmitCasts = true)]
public partial class HTMLTableElement : HTMLElement
{

	// HTMLTableElement
	public HTMLTableCaptionElement caption {get { return default(HTMLTableCaptionElement); } set {}}
	public HTMLElement createCaption() { return default(HTMLElement); }
	public void deleteCaption() {}
	public HTMLTableSectionElement tHead {get { return default(HTMLTableSectionElement); } set {}}
	public HTMLElement createTHead() { return default(HTMLElement); }
	public void deleteTHead() {}
	public HTMLTableSectionElement tFoot {get { return default(HTMLTableSectionElement); } set {}}
	public HTMLElement createTFoot() { return default(HTMLElement); }
	public void deleteTFoot() {}
	public HTMLCollection tBodies {get { return default(HTMLCollection); } }
	public HTMLElement createTBody() { return default(HTMLElement); }
	public HTMLCollection rows {get { return default(HTMLCollection); } }
	public HTMLElement insertRow() { return default(HTMLElement); }
	public HTMLElement insertRow(int index) { return default(HTMLElement); }
	public void deleteRow(int index) {}
	public string summary {get { return default(string); } set {}}

	// HTMLTableElement-31
	public string align {get { return default(string); } set {}}
	public string bgColor {get { return default(string); } set {}}
	public string border {get { return default(string); } set {}}
	public string cellPadding {get { return default(string); } set {}}
	public string cellSpacing {get { return default(string); } set {}}
	public string frame {get { return default(string); } set {}}
	public string rules {get { return default(string); } set {}}
	public string width {get { return default(string); } set {}}
}

}