using SharpKit.JavaScript;
//AutoGenerated

namespace org.w3c.dom.html
{

    public interface HTMLTableCellElement : HTMLElement
    {
        // HTMLTableCellElement
        int colSpan {get;set;}
        int rowSpan {get;set;}
        DOMSettableTokenList headers {get;set;}
        int cellIndex {get;}
        // HTMLTableCellElement-33
        JsString abbr {get;set;}
        JsString align {get;set;}
        JsString axis {get;set;}
        JsString bgColor {get;set;}
        JsString ch {get;set;}
        JsString chOff {get;set;}
        JsString height {get;set;}
        bool noWrap {get;set;}
        JsString vAlign {get;set;}
        JsString width {get;set;}
    }

}
