//Generated by a tool of Sebastian Loncar

namespace org.w3c.dom.html
{

using SharpKit.JavaScript;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields=true, OmitCasts = true)]
public partial class ImageData
{

	// ImageData
	public int width {get;private set;}
	public int height {get;private set;}
	public CanvasPixelArray data {get;private set;}
}

}