//Generated by a tool of Sebastian Loncar

namespace org.w3c.dom.html
{

using SharpKit.JavaScript;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields=true, OmitCasts = true)]
public partial class Navigator
{

	// Navigator

	// NavigatorID
	public string appName {get { return default(string); } }
	public string appVersion {get { return default(string); } }
	public string platform {get { return default(string); } }
	public string userAgent {get { return default(string); } }

	// NavigatorOnLine
	public bool onLine {get { return default(bool); } }

	// NavigatorAbilities
	public void registerProtocolHandler(string scheme, string url, string title) {}
	public void registerContentHandler(string mimeType, string url, string title) {}
	public void yieldForStorageUpdates() {}
}

}