//Generated by a tool of Sebastian Loncar

namespace org.w3c.dom.html
{

using SharpKit.JavaScript;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields=true, OmitCasts = true)]
public partial class Screen
{

	// Screen
	public int availWidth {get { return default(int); } }
	public int availHeight {get { return default(int); } }
	public int width {get { return default(int); } }
	public int height {get { return default(int); } }
	public int colorDepth {get { return default(int); } }
	public int pixelDepth {get { return default(int); } }
}

}