//Generated by a tool of Sebastian Loncar

namespace org.w3c.dom.html
{

using SharpKit.JavaScript;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields=true, OmitCasts = true)]
public partial class ValidityState
{

	// ValidityState
	public bool valueMissing {get { return default(bool); } }
	public bool typeMismatch {get { return default(bool); } }
	public bool patternMismatch {get { return default(bool); } }
	public bool tooLong {get { return default(bool); } }
	public bool rangeUnderflow {get { return default(bool); } }
	public bool rangeOverflow {get { return default(bool); } }
	public bool stepMismatch {get { return default(bool); } }
	public bool customError {get { return default(bool); } }
	public bool valid {get { return default(bool); } }
}

}