// Generated by SharpKit.QooxDoo.Generator
using System;
using System.Collections.Generic;
using SharpKit.Html;
using SharpKit.JavaScript;

namespace qx.ui.virtualx.cell
{
    /// <summary>
	/// <para>EXPERIMENTAL!</para>
	/// </summary>
	[JsType(JsMode.Prototype, Name = "qx.ui.virtual.cell.Image", OmitOptionalParameters = true, Export = false)]
    public partial class Image : qx.ui.virtualx.cell.AbstractImage
    {
		#region Properties

		[JsProperty(Name = "appearance", NativeField = true)]
		public object Appearance { get; set; }

		#endregion Properties

		#region Methods

		public Image() { throw new NotImplementedException(); }

		#endregion Methods
    }
}