/*Generated by SharpKit 5 v4.29.7000*/
$(OnReady);
function OnReady()
{
    $("#numerictextbox").kendoNumericTextBox({change:onChange,spin:onSpin});
};
function onChange()
{
    kendoConsole.log("Change :: " + this.value());
};
function onSpin()
{
    kendoConsole.log("Spin :: " + this.value());
};
