/*Generated by SharpKit 5 v4.30.1000*/
$(OnReady);
function OnReady()
{
    $("#numerictextbox").kendoNumericTextBox( {change: onChange, spin: onSpin});
};
function onChange()
{
    kendoConsole.log("Change :: " + this.value());
};
function onSpin()
{
    kendoConsole.log("Spin :: " + this.value());
};
