//Generated by a tool of Sebastian Loncar

namespace SharpKit.Html
{

using SharpKit.JavaScript;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields = true, OmitCasts = true)]
public partial class HtmlQuoteElement : HtmlElement
{

	// HTMLQuoteElement
	public JsString cite {get; set; }
}

}