//Generated by a tool of Sebastian Loncar

namespace SharpKit.Html
{

    using SharpKit.JavaScript;

    [JsType(JsMode.Prototype, Export = false, PropertiesAsFields = true, OmitCasts = true)]
    public partial class HtmlElement : Element
    {

        // HTMLElement
        public NodeList getElementsByClassName(string classNames) { return default(NodeList); }
        public JsString innerHTML { get; set; }
        public JsString outerHTML { get; set; }
        public void insertAdjacentHtml(string position, string text) { }
        public JsString id { get; set; }
        public JsString title { get; set; }
        public JsString lang { get; set; }
        public JsString dir { get; set; }
        public JsString className { get; set; }
        public DOMTokenList classList { get; private set; }
        public DOMStringMap dataset { get; private set; }
        public bool hidden { get; set; }
        public void click() { }
        public void scrollIntoView() { }
        public void scrollIntoView(bool top) { }
        public int tabIndex { get; set; }
        public void focus() { }
        public void blur() { }
        public JsString accessKey { get; set; }
        public JsString accessKeyLabel { get; private set; }
        public bool draggable { get; set; }
        public JsString contentEditable { get; set; }
        public bool isContentEditable { get; private set; }
        public HtmlMenuElement contextMenu { get; set; }
        public JsString spellcheck { get; set; }
        public JsString commandType { get; private set; }
        public JsString label { get; private set; }
        public JsString icon { get; private set; }
        public bool disabled { get; private set; }
        public bool @checked { get; private set; }
        public CSSStyleDeclaration style { get; private set; }
        public EventListener onabort { get; set; }
        public EventListener onblur { get; set; }
        public EventListener oncanplay { get; set; }
        public EventListener oncanplaythrough { get; set; }
        public EventListener onchange { get; set; }
        public EventListener onclick { get; set; }
        public EventListener oncontextmenu { get; set; }
        public EventListener ondblclick { get; set; }
        public EventListener ondrag { get; set; }
        public EventListener ondragend { get; set; }
        public EventListener ondragenter { get; set; }
        public EventListener ondragleave { get; set; }
        public EventListener ondragover { get; set; }
        public EventListener ondragstart { get; set; }
        public EventListener ondrop { get; set; }
        public EventListener ondurationchange { get; set; }
        public EventListener onemptied { get; set; }
        public EventListener onended { get; set; }
        public EventListener onerror { get; set; }
        public EventListener onfocus { get; set; }
        public EventListener onformchange { get; set; }
        public EventListener onforminput { get; set; }
        public EventListener oninput { get; set; }
        public EventListener oninvalid { get; set; }
        public EventListener onkeydown { get; set; }
        public EventListener onkeypress { get; set; }
        public EventListener onkeyup { get; set; }
        public EventListener onload { get; set; }
        public EventListener onloadeddata { get; set; }
        public EventListener onloadedmetadata { get; set; }
        public EventListener onloadstart { get; set; }
        public EventListener onmousedown { get; set; }
        public EventListener onmousemove { get; set; }
        public EventListener onmouseout { get; set; }
        public EventListener onmouseover { get; set; }
        public EventListener onmouseup { get; set; }
        public EventListener onmousewheel { get; set; }
        public EventListener onpause { get; set; }
        public EventListener onplay { get; set; }
        public EventListener onplaying { get; set; }
        public EventListener onprogress { get; set; }
        public EventListener onratechange { get; set; }
        public EventListener onreadystatechange { get; set; }
        public EventListener onscroll { get; set; }
        public EventListener onseeked { get; set; }
        public EventListener onseeking { get; set; }
        public EventListener onselect { get; set; }
        public EventListener onshow { get; set; }
        public EventListener onstalled { get; set; }
        public EventListener onsubmit { get; set; }
        public EventListener onsuspend { get; set; }
        public EventListener ontimeupdate { get; set; }
        public EventListener onvolumechange { get; set; }
        public EventListener onwaiting { get; set; }

        // HTMLElement-3
        public Element offsetParent { get; private set; }
        public int offsetTop { get; private set; }
        public int offsetLeft { get; private set; }
        public int offsetWidth { get; private set; }
        public int offsetHeight { get; private set; }

        // HTMLElement-38
        public bool itemScope { get; set; }
        public JsString itemType { get; set; }
        public JsString itemId { get; set; }
        public DOMSettableTokenList itemRef { get; set; }
        public DOMSettableTokenList itemProp { get; set; }
        public HtmlPropertiesCollection properties { get; private set; }
        public object itemValue { get; set; }
    }

}