//Generated by a tool of Sebastian Loncar

namespace SharpKit.Html
{

using SharpKit.JavaScript;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields = true, OmitCasts = true)]
public partial class HtmlTitleElement : HtmlElement
{

	// HTMLTitleElement
	public JsString text {get; set; }
}

}