//Generated by a tool of Sebastian Loncar

namespace SharpKit.Html
{

using SharpKit.JavaScript;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields = true, OmitCasts = true)]
public partial class HtmlOptionsCollection : HtmlCollection
{

	// HTMLOptionsCollection
	public int length {get; set; }
	[JsProperty(NativeIndexer = true)]
	public object this[string name] {get { return default(object); } }
	public void add(HtmlElement element) {}
	public void add(HtmlElement element, HtmlElement before) {}
	public void add(HtmlElement element, int before) {}
	public void remove(int index) {}
}

}