//Generated by a tool of Sebastian Loncar

namespace SharpKit.Html
{

using SharpKit.JavaScript;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields = true, OmitCasts = true)]
public partial class HtmlMenuElement : HtmlElement
{

	// HTMLMenuElement
	public JsString type {get; set; }
	public JsString label {get; set; }

	// HTMLMenuElement-23
	public bool compact {get; set; }
}

}