/*Generated by SharpKit 5 v4.29.7000*/
$(OnReady);
function OnReady()
{
     $.fx.speeds._default = 1000;;
    $("#dialog").dialog({autoOpen:false,show:"blind",hide:"explode"});
    $("#opener").click(function(e)
    {
        $("#dialog").dialog("open");
        return false;
    });
};
