//Generated by a tool of Sebastian Loncar

namespace org.w3c.dom.workers
{

using SharpKit.JavaScript;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields=true, OmitCasts = true)]
public partial class WorkerLocation
{

	// WorkerLocation
	public string href {get { return default(string); } }
	public string protocol {get { return default(string); } }
	public string host {get { return default(string); } }
	public string hostname {get { return default(string); } }
	public string port {get { return default(string); } }
	public string pathname {get { return default(string); } }
	public string search {get { return default(string); } }
	public string hash {get { return default(string); } }
}

}