/*Generated by SharpKit 5 v4.29.7000*/
$(OnReady);
function OnReady()
{
    var fields=new Object();
    fields["OrderID"] = {type:"number"};
    fields["ShipCountry"] = {type:"string"};
    fields["ShipName"] = {type:"string"};
    fields["ShipAddress"] = {type:"string"};
     columns: ['OrderID','ShipCountry','ShipName',{field: 'ShipAddress',filterable: false}];
    $("#grid").kendoGrid(
    {
        dataSource:
        {
            type:"odata",
            schema:
            {
                model:{fields:fields}
            },
            pageSize:10,
            serverPaging:true,
            serverFiltering:true,
            serverSorting:true
        },
        height:250,
        sortable:true,
        filterable:true,
        pageable:true
    });
};
