/*Generated by SharpKit 5 v4.29.7000*/
$(OnReady);
function OnReady()
{
    var x="shuki";
    var icon={header:"ui-icon-circle-arrow-e",headerSelected:"ui-icon-circle-arrow-s"};
    $("#accordion").accordion({icons:icon});
    $("#toggle").button().toggle(function(e)
    {
        $("#accordion").accordion("option","icons",false);
    },function(e)
    {
        $("#accordion").accordion("option","icons",icon);
    });
};
