/*Generated by SharpKit 5 v5.00.0000*/
$(OnReady);
function OnReady()
{
    $("#accordion").accordion( {header: ">div > h3"}).sortable(
    {
        axis: "y",
        handle: "h3",
        stop: function (e, ui)
        {
            ui.item.children("h3").triggerHandler("focusout");
        }
    });
};
