//Generated by a tool of Sebastian Loncar

namespace org.w3c.dom.xpath
{

using SharpKit.JavaScript;
using DOMException = org.w3c.dom.DOMException;
using Node = org.w3c.dom.Node;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields=true, OmitCasts = true)]
public partial class XPathEvaluator
{

	// XPathEvaluator
	public XPathExpression createExpression(string expression, XPathNSResolver resolver) { return default(XPathExpression); }
	public XPathNSResolver createNSResolver(Node nodeResolver) { return default(XPathNSResolver); }
	public object evaluate(string expression, Node contextNode, XPathNSResolver resolver, short type, object result) { return default(object); }
}

}