//Generated by a tool of Sebastian Loncar

namespace org.w3c.dom.indexeddb
{

using SharpKit.JavaScript;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields=true, OmitCasts = true)]
public partial class IDBCursorSync : IDBCursor
{

	// IDBCursorSync
	public object key {get;private set;}
	public object value {get;set;}
	public long count {get;private set;}
	public bool _continue() { return default(bool); }
	public bool _continue(object key) { return default(bool); }
	public void remove() {}
}

}