using SharpKit.JavaScript;
//AutoGenerated

namespace org.w3c.dom.indexeddb
{

    using DOMStringList = org.w3c.dom.DOMStringList;

    public interface IDBDatabase
    {
        // IDBDatabase
        JsString name {get;}
        JsString description {get;}
        JsString version {get;}
        DOMStringList objectStores {get;}
        DOMStringList indexes {get;}
        IDBTransaction currentTransaction {get;}
    }

}
