//Generated by a tool of Sebastian Loncar

namespace org.w3c.dom.indexeddb
{

using SharpKit.JavaScript;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields=true, OmitCasts = true)]
public partial class IDBEnvironment
{

	// IDBEnvironment
	public IndexedDatabaseRequest indexedDB {get;private set;}
}

}