//Generated by a tool of Sebastian Loncar

namespace org.w3c.dom.indexeddb
{

using SharpKit.JavaScript;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields=true, OmitCasts = true)]
public partial class IDBEnvironmentSync
{

	// IDBEnvironmentSync
	public IndexedDatabase indexedDB {get;private set;}
}

}