using SharpKit.JavaScript;
//AutoGenerated

namespace org.w3c.dom.webgl
{

    public interface WebGLShortArray_Constructor
    {
        // Constructor
        WebGLShortArray createInstance(int length);
        WebGLShortArray createInstance(WebGLShortArray array);
        WebGLShortArray createInstance(short[] array);
        WebGLShortArray createInstance(WebGLArrayBuffer buffer);
        WebGLShortArray createInstance(WebGLArrayBuffer buffer, int byteOffset);
        WebGLShortArray createInstance(WebGLArrayBuffer buffer, int byteOffset, int length);
    }

}
