//AutoGenerated

namespace org.w3c.dom.webgl
{

    public interface WebGLObjectArray
    {
        // WebGLObjectArray
        int length {get;}
        WebGLObject get(int index);
    }

}