using SharpKit.JavaScript;
//AutoGenerated

namespace org.w3c.dom.webgl
{

    public interface WebGLFloatArray_Constructor
    {
        // Constructor
        WebGLFloatArray createInstance(int length);
        WebGLFloatArray createInstance(WebGLFloatArray array);
        WebGLFloatArray createInstance(float[] array);
        WebGLFloatArray createInstance(WebGLArrayBuffer buffer);
        WebGLFloatArray createInstance(WebGLArrayBuffer buffer, int byteOffset);
        WebGLFloatArray createInstance(WebGLArrayBuffer buffer, int byteOffset, int length);
    }

}
