//Generated by a tool of Sebastian Loncar

namespace SharpKit.Html
{

using SharpKit.JavaScript;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields = true, OmitCasts = true)]
public partial class HtmlFormElement : HtmlElement
{

	// HTMLFormElement
	public JsString acceptCharset {get; set; }
	public JsString action {get; set; }
	public bool autocomplete {get; set; }
	public JsString enctype {get; set; }
	public JsString method {get; set; }
	public JsString name {get; set; }
	public bool noValidate {get; set; }
	public JsString target {get; set; }
	public HtmlFormControlsCollection elements {get; private set; }
	public int length {get; private set; }
	[JsProperty(NativeIndexer = true)]
	public object this[int index] {get { return default(object); } }
	[JsProperty(NativeIndexer = true)]
	public object this[string name] {get { return default(object); } }
	public void submit() {}
	public void reset() {}
	public bool checkValidity() { return default(bool); }
	public void dispatchFormInput() {}
	public void dispatchFormChange() {}
}

}