//Generated by a tool of Sebastian Loncar

namespace org.w3c.dom.events
{

using SharpKit.JavaScript;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields=true, OmitCasts = true)]
public partial class Event
{

	// Event
	public static short CAPTURING_PHASE = 1;
	public static short AT_TARGET = 2;
	public static short BUBBLING_PHASE = 3;
	public string type {get { return default(string); } }
	public EventTarget target {get { return default(EventTarget); } }
	public EventTarget currentTarget {get { return default(EventTarget); } }
	public short eventPhase {get { return default(short); } }
	public bool bubbles {get { return default(bool); } }
	public bool cancelable {get { return default(bool); } }
	public long timeStamp {get { return default(long); } }
	public void stopPropagation() {}
	public void preventDefault() {}
	public void initEvent(string eventTypeArg, bool canBubbleArg, bool cancelableArg) {}
	public void stopImmediatePropagation() {}
	public bool defaultPrevented {get { return default(bool); } }
	public bool trusted {get { return default(bool); } }
}

}