//Generated by a tool of Sebastian Loncar

namespace org.w3c.dom.events
{

using SharpKit.JavaScript;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields=true, OmitCasts = true)]
public partial class ProgressEvent : Event
{

	// ProgressEvent
	public bool lengthComputable {get;private set;}
	public int loaded {get;private set;}
	public int total {get;private set;}
	public void initProgressEvent(string typeArg, bool canBubbleArg, bool cancelableArg, bool lengthComputableArg, int loadedArg, int totalArg) {}
	public void initProgressEventNS(string namespaceURI, string typeArg, bool canBubbleArg, bool cancelableArg, bool lengthComputableArg, int loadedArg, int totalArg) {}
}

}