//Generated by a tool of Sebastian Loncar

namespace org.w3c.dom.css
{

using SharpKit.JavaScript;
using DOMException = org.w3c.dom.DOMException;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields=true, OmitCasts = true)]
public partial class CSS2Properties
{

	// CSS2Properties
	public string azimuth {get;set;}
	public string background {get;set;}
	public string backgroundAttachment {get;set;}
	public string backgroundColor {get;set;}
	public string backgroundImage {get;set;}
	public string backgroundPosition {get;set;}
	public string backgroundRepeat {get;set;}
	public string border {get;set;}
	public string borderCollapse {get;set;}
	public string borderColor {get;set;}
	public string borderSpacing {get;set;}
	public string borderStyle {get;set;}
	public string borderTop {get;set;}
	public string borderRight {get;set;}
	public string borderBottom {get;set;}
	public string borderLeft {get;set;}
	public string borderTopColor {get;set;}
	public string borderRightColor {get;set;}
	public string borderBottomColor {get;set;}
	public string borderLeftColor {get;set;}
	public string borderTopStyle {get;set;}
	public string borderRightStyle {get;set;}
	public string borderBottomStyle {get;set;}
	public string borderLeftStyle {get;set;}
	public string borderTopWidth {get;set;}
	public string borderRightWidth {get;set;}
	public string borderBottomWidth {get;set;}
	public string borderLeftWidth {get;set;}
	public string borderWidth {get;set;}
	public string bottom {get;set;}
	public string captionSide {get;set;}
	public string clear {get;set;}
	public string clip {get;set;}
	public string color {get;set;}
	public string content {get;set;}
	public string counterIncrement {get;set;}
	public string counterReset {get;set;}
	public string cue {get;set;}
	public string cueAfter {get;set;}
	public string cueBefore {get;set;}
	public string cursor {get;set;}
	public string direction {get;set;}
	public string display {get;set;}
	public string elevation {get;set;}
	public string emptyCells {get;set;}
	public string cssFloat {get;set;}
	public string font {get;set;}
	public string fontFamily {get;set;}
	public string fontSize {get;set;}
	public string fontSizeAdjust {get;set;}
	public string fontStretch {get;set;}
	public string fontStyle {get;set;}
	public string fontVariant {get;set;}
	public string fontWeight {get;set;}
	public string height {get;set;}
	public string left {get;set;}
	public string letterSpacing {get;set;}
	public string lineHeight {get;set;}
	public string listStyle {get;set;}
	public string listStyleImage {get;set;}
	public string listStylePosition {get;set;}
	public string listStyleType {get;set;}
	public string margin {get;set;}
	public string marginTop {get;set;}
	public string marginRight {get;set;}
	public string marginBottom {get;set;}
	public string marginLeft {get;set;}
	public string markerOffset {get;set;}
	public string marks {get;set;}
	public string maxHeight {get;set;}
	public string maxWidth {get;set;}
	public string minHeight {get;set;}
	public string minWidth {get;set;}
	public string orphans {get;set;}
	public string outline {get;set;}
	public string outlineColor {get;set;}
	public string outlineStyle {get;set;}
	public string outlineWidth {get;set;}
	public string overflow {get;set;}
	public string padding {get;set;}
	public string paddingTop {get;set;}
	public string paddingRight {get;set;}
	public string paddingBottom {get;set;}
	public string paddingLeft {get;set;}
	public string page {get;set;}
	public string pageBreakAfter {get;set;}
	public string pageBreakBefore {get;set;}
	public string pageBreakInside {get;set;}
	public string pause {get;set;}
	public string pauseAfter {get;set;}
	public string pauseBefore {get;set;}
	public string pitch {get;set;}
	public string pitchRange {get;set;}
	public string playDuring {get;set;}
	public string position {get;set;}
	public string quotes {get;set;}
	public string richness {get;set;}
	public string right {get;set;}
	public string size {get;set;}
	public string speak {get;set;}
	public string speakHeader {get;set;}
	public string speakNumeral {get;set;}
	public string speakPunctuation {get;set;}
	public string speechRate {get;set;}
	public string stress {get;set;}
	public string tableLayout {get;set;}
	public string textAlign {get;set;}
	public string textDecoration {get;set;}
	public string textIndent {get;set;}
	public string textShadow {get;set;}
	public string textTransform {get;set;}
	public string top {get;set;}
	public string unicodeBidi {get;set;}
	public string verticalAlign {get;set;}
	public string visibility {get;set;}
	public string voiceFamily {get;set;}
	public string volume {get;set;}
	public string whiteSpace {get;set;}
	public string widows {get;set;}
	public string width {get;set;}
	public string wordSpacing {get;set;}
	public string zIndex {get;set;}
}

}