//Generated by a tool of Sebastian Loncar

namespace org.w3c.dom.css
{

using SharpKit.JavaScript;
using StyleSheet = org.w3c.dom.stylesheets.StyleSheet;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields=true, OmitCasts = true)]
public partial class CSSStyleSheet : StyleSheet
{

	// CSSStyleSheet
	public CSSRule ownerRule {get { return default(CSSRule); } }
	public CSSRule cssRules {get { return default(CSSRule); } }
	public int insertRule(string rule, int index) { return default(int); }
	public void deleteRule(int index) {}
}

}