//@AutoGenerated
function tbNewTask_onkeypress(sender, e)
{
	if (e.keyCode == 13)
	{
		sender.blur();
		return false;
	}
	return true;
}
function tbNewTask_onblur(sender, e)
{
	if (sender.value == null || sender.value == "")
		return false;
	var ul = document.getElementById("ulTaskList");
	var li = document.createElement("li");
	li.appendChild(document.createTextNode(sender.value));
	var liNewTask = document.getElementById("liNewTask");
	liNewTask.insertAdjacentElement("beforeBegin", li);
	sender.value = "";
	sender.focus();
	return true;
}
