//***************************************************
//* This file was generated by tool
//* SharpKit
//***************************************************
using System;
using System.Collections.Generic;
using SharpKit.JavaScript;
namespace YUI_
{
    /// <summary>
    /// Provides pre-built result highlighters for AutoComplete.
    /// </summary>
    public partial class AutoCompleteHighlighters
    {
        /// <summary>
        /// Highlights any individual query character that occurs anywhere in a result.
        /// Case-insensitive.
        /// </summary>
        public YUI_.Array charMatch(object query, YUI_.Array results){return null;}
        /// <summary>
        /// Case-sensitive version of `charMatch()`.
        /// </summary>
        public YUI_.Array charMatchCase(object query, YUI_.Array results){return null;}
        /// <summary>
        /// Accent-folding version of `charMatch()`.
        /// </summary>
        public YUI_.Array charMatchFold(object query, YUI_.Array results){return null;}
        /// <summary>
        /// Highlights the complete query as a phrase anywhere within a result. Case-
        /// insensitive.
        /// </summary>
        public YUI_.Array phraseMatch(object query, YUI_.Array results){return null;}
        /// <summary>
        /// Case-sensitive version of `phraseMatch()`.
        /// </summary>
        public YUI_.Array phraseMatchCase(object query, YUI_.Array results){return null;}
        /// <summary>
        /// Accent-folding version of `phraseMatch()`.
        /// </summary>
        public YUI_.Array phraseMatchFold(object query, YUI_.Array results){return null;}
        /// <summary>
        /// Highlights the complete query as a phrase at the beginning of a result.
        /// Case-insensitive.
        /// </summary>
        public YUI_.Array startsWith(object query, YUI_.Array results){return null;}
        /// <summary>
        /// Case-sensitive version of `startsWith()`.
        /// </summary>
        public YUI_.Array startsWithCase(object query, YUI_.Array results){return null;}
        /// <summary>
        /// Accent-folding version of `startsWith()`.
        /// </summary>
        public YUI_.Array startsWithFold(object query, YUI_.Array results){return null;}
        /// <summary>
        /// Highlights portions of results in which words from the query match either
        /// whole words or parts of words in the result. Non-word characters like
        /// whitespace and certain punctuation are ignored. Case-insensitive.
        /// </summary>
        public YUI_.Array subWordMatch(object query, YUI_.Array results){return null;}
        /// <summary>
        /// Case-sensitive version of `subWordMatch()`.
        /// </summary>
        public YUI_.Array subWordMatchCase(object query, YUI_.Array results){return null;}
        /// <summary>
        /// Accent-folding version of `subWordMatch()`.
        /// </summary>
        public YUI_.Array subWordMatchFold(object query, YUI_.Array results){return null;}
        /// <summary>
        /// Highlights individual words in results that are also in the query. Non-word
        /// characters like punctuation are ignored. Case-insensitive.
        /// </summary>
        public YUI_.Array wordMatch(object query, YUI_.Array results){return null;}
        /// <summary>
        /// Case-sensitive version of `wordMatch()`.
        /// </summary>
        public YUI_.Array wordMatchCase(object query, YUI_.Array results){return null;}
        /// <summary>
        /// Accent-folding version of `wordMatch()`.
        /// </summary>
        public YUI_.Array wordMatchFold(object query, YUI_.Array results){return null;}
    }
}
