//***************************************************
//* This file was generated by tool
//* SharpKit
//***************************************************
using System;
using System.Collections.Generic;
using SharpKit.JavaScript;
namespace YUI_
{
    /// <summary>
    /// DataSource plugin adds cache functionality.
    /// </summary>
    public partial class DataSourceCache : YUI_.Cache
    {
    }
}
