/*Generated by SharpKit 5 v4.29.7000*/
$(OnReady);
function OnReady()
{
    $("#slider-range").slider(
    {
        orientation:"vertical",
        range:true,
        values:[17,67],
        slide:function(e,ui)
        {
            $("#amount").val("$" + ui.value + " - $" + ui.value);
        }
    });
    $("#amount").val("$" + $("#slider-range").slider("values",0) + " - $" + $("#slider-range").slider("values",1));
};
