//Generated by a tool of Sebastian Loncar

namespace SharpKit.Html
{

using SharpKit.JavaScript;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields = true, OmitCasts = true)]
public partial class Screen
{

	// Screen
	public int availWidth {get; private set; }
	public int availHeight {get; private set; }
	public int width {get; private set; }
	public int height {get; private set; }
	public int colorDepth {get; private set; }
	public int pixelDepth {get; private set; }
}

}