// Generated by SharpKit.QooxDoo.Generator
using System;
using System.Collections.Generic;
using SharpKit.Html;
using SharpKit.JavaScript;

namespace qx.bom
{
    /// <summary>
	/// <para>Implements an iFrame based history manager for IE 6/7/8.</para>
	/// <para>Creates a hidden iFrame and uses document.write to store entries in the
	/// history browser&#8217;s stack.</para>
	/// </summary>
	[JsType(JsMode.Prototype, Name = "qx.bom.IframeHistory", OmitOptionalParameters = true, Export = false)]
    public partial class IframeHistory : qx.bom.History
    {
		#region Methods

		public IframeHistory() { throw new NotImplementedException(); }

		[JsMethod(Name = "addToHistory")]
		public void AddToHistory(object state, object newTitle) { throw new NotImplementedException(); }

		#endregion Methods
    }
}