//Generated by a tool of Sebastian Loncar

namespace org.w3c.dom.svg
{

using SharpKit.JavaScript;
using DOMException = org.w3c.dom.DOMException;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields=true, OmitCasts = true)]
public partial class GetSVGDocument
{

	// GetSVGDocument
	public SVGDocument sVGDocument {get { return default(SVGDocument); } }
}

}