//Generated by a tool of Sebastian Loncar

namespace org.w3c.dom.svg
{

using SharpKit.JavaScript;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields=true, OmitCasts = true)]
public partial class SVGAnimatedRect
{

	// SVGAnimatedRect
	public SVGRect baseVal {get;private set;}
	public SVGRect animVal {get;private set;}
}

}