//Generated by a tool of Sebastian Loncar

namespace org.w3c.dom.svg
{

using SharpKit.JavaScript;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields=true, OmitCasts = true)]
public partial class SVGAltGlyphElement : SVGTextPositioningElement
{

	// SVGAltGlyphElement
	public string glyphRef {get { return default(string); } set {}}
	public string format {get { return default(string); } set {}}
}

}