//AutoGenerated

namespace org.w3c.dom.svg
{

    using DOMException = org.w3c.dom.DOMException;
    using ElementTimeControl = org.w3c.dom.smil.ElementTimeControl;

    public interface SVGAnimationElement : SVGElement, SVGTests, SVGExternalResourcesRequired, org.w3c.dom.smil.ElementTimeControl
    {
        // SVGAnimationElement
        SVGElement targetElement {get;}
        float startTime {get;}
        float currentTime {get;}
//JAVA TO C# CONVERTER WARNING: Method 'throws' clauses are not available in .NET:
//ORIGINAL LINE: public float getSimpleDuration() throws org.w3c.dom.DOMException;
        float simpleDuration {get;}
    }

}