//AutoGenerated

namespace org.w3c.dom.svg
{

    public interface SVGAnimatedInteger
    {
        // SVGAnimatedInteger
        int baseVal {get;set;}
        int animVal {get;}
    }

}