//Generated by a tool of Sebastian Loncar

namespace org.w3c.dom.svg
{

using SharpKit.JavaScript;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields=true, OmitCasts = true)]
public partial class SVGCircleElement : SVGElement
{

	// SVGCircleElement
	public SVGAnimatedLength cx {get { return default(SVGAnimatedLength); } }
	public SVGAnimatedLength cy {get { return default(SVGAnimatedLength); } }
	public SVGAnimatedLength r {get { return default(SVGAnimatedLength); } }
}

}