//Generated by a tool of Sebastian Loncar

namespace org.w3c.dom.svg
{

using SharpKit.JavaScript;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields=true, OmitCasts = true)]
public partial class SVGDocument
{

	// SVGDocument
	public string title {get;private set;}
	public string referrer {get;private set;}
	public string domain {get;private set;}
	public string uRL {get;private set;}
	public SVGSVGElement rootElement {get;private set;}
}

}