//Generated by a tool of Sebastian Loncar

namespace org.w3c.dom.svg
{

using SharpKit.JavaScript;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields=true, OmitCasts = true)]
public partial class SVGFESpotLightElement : SVGElement
{

	// SVGFESpotLightElement
	public SVGAnimatedNumber x {get { return default(SVGAnimatedNumber); } }
	public SVGAnimatedNumber y {get { return default(SVGAnimatedNumber); } }
	public SVGAnimatedNumber z {get { return default(SVGAnimatedNumber); } }
	public SVGAnimatedNumber pointsAtX {get { return default(SVGAnimatedNumber); } }
	public SVGAnimatedNumber pointsAtY {get { return default(SVGAnimatedNumber); } }
	public SVGAnimatedNumber pointsAtZ {get { return default(SVGAnimatedNumber); } }
	public SVGAnimatedNumber specularExponent {get { return default(SVGAnimatedNumber); } }
	public SVGAnimatedNumber limitingConeAngle {get { return default(SVGAnimatedNumber); } }
}

}