//AutoGenerated

namespace org.w3c.dom.svg
{

    public interface SVGGlyphRefElement : SVGElement, SVGURIReference, SVGStylable
    {
        // SVGGlyphRefElement
        string glyphRef {get;set;}
        string format {get;set;}
        float x {get;set;}
        float y {get;set;}
        float dx {get;set;}
        float dy {get;set;}
    }

}