//Generated by a tool of Sebastian Loncar

namespace org.w3c.dom.svg
{

using SharpKit.JavaScript;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields=true, OmitCasts = true)]
public partial class SVGGradientElement : SVGElement
{

	// SVGGradientElement
	public static short SVG_SPREADMETHOD_UNKNOWN = 0;
	public static short SVG_SPREADMETHOD_PAD = 1;
	public static short SVG_SPREADMETHOD_REFLECT = 2;
	public static short SVG_SPREADMETHOD_REPEAT = 3;
	public SVGAnimatedEnumeration gradientUnits {get { return default(SVGAnimatedEnumeration); } }
	public SVGAnimatedTransformList gradientTransform {get { return default(SVGAnimatedTransformList); } }
	public SVGAnimatedEnumeration spreadMethod {get { return default(SVGAnimatedEnumeration); } }
}

}