//Generated by a tool of Sebastian Loncar

namespace org.w3c.dom.svg
{

using SharpKit.JavaScript;
using DOMException = org.w3c.dom.DOMException;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields=true, OmitCasts = true)]
public partial class SVGLengthList
{

	// SVGLengthList
	public int numberOfItems {get { return default(int); } }
	public void clear() {}
	public SVGLength initialize(SVGLength newItem) { return default(SVGLength); }
	public SVGLength getItem(int index) { return default(SVGLength); }
	public SVGLength insertItemBefore(SVGLength newItem, int index) { return default(SVGLength); }
	public SVGLength replaceItem(SVGLength newItem, int index) { return default(SVGLength); }
	public SVGLength removeItem(int index) { return default(SVGLength); }
	public SVGLength appendItem(SVGLength newItem) { return default(SVGLength); }
}

}