using SharpKit.JavaScript;
//AutoGenerated

namespace org.w3c.dom.svg
{

    public interface SVGLangSpace
    {
        // SVGLangSpace
        JsString xmllang {get;set;}
        JsString xmlspace {get;set;}
    }

}
