using SharpKit.JavaScript;
//AutoGenerated

namespace org.w3c.dom.svg
{

    public interface SVGMPathElement : SVGElement, SVGURIReference, SVGExternalResourcesRequired
    {
        // SVGMPathElement
    }

}
