using SharpKit.JavaScript;
//AutoGenerated

namespace org.w3c.dom.svg
{

    public interface SVGMissingGlyphElement : SVGElement, SVGStylable
    {
        // SVGMissingGlyphElement
    }

}
