//Generated by a tool of Sebastian Loncar

namespace org.w3c.dom.svg
{

using SharpKit.JavaScript;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields=true, OmitCasts = true)]
public partial class SVGPathSegCurvetoCubicSmoothRel : SVGPathSeg
{

	// SVGPathSegCurvetoCubicSmoothRel
	public float x {get;set;}
	public float y {get;set;}
	public float x2 {get;set;}
	public float y2 {get;set;}
}

}