//AutoGenerated

namespace org.w3c.dom.svg
{

    public interface SVGPathSegLinetoHorizontalAbs : SVGPathSeg
    {
        // SVGPathSegLinetoHorizontalAbs
        float x {get;set;}
    }

}