//AutoGenerated

namespace org.w3c.dom.svg
{

    using DOMException = org.w3c.dom.DOMException;

    public interface SVGStringList
    {
        // SVGStringList
        int numberOfItems {get;}
//TODO:
//ORIGINAL LINE: public void clear() throws org.w3c.dom.DOMException;
        void clear();
//TODO:
//ORIGINAL LINE: public String initialize(String newItem) throws org.w3c.dom.DOMException, SVGException;
        string initialize(string newItem);
//TODO:
//ORIGINAL LINE: public String getItem(int index) throws org.w3c.dom.DOMException;
        string getItem(int index);
//TODO:
//ORIGINAL LINE: public String insertItemBefore(String newItem, int index) throws org.w3c.dom.DOMException, SVGException;
        string insertItemBefore(string newItem, int index);
//TODO:
//ORIGINAL LINE: public String replaceItem(String newItem, int index) throws org.w3c.dom.DOMException, SVGException;
        string replaceItem(string newItem, int index);
//TODO:
//ORIGINAL LINE: public String removeItem(int index) throws org.w3c.dom.DOMException;
        string removeItem(int index);
//TODO:
//ORIGINAL LINE: public String appendItem(String newItem) throws org.w3c.dom.DOMException, SVGException;
        string appendItem(string newItem);
    }

}