//AutoGenerated

namespace org.w3c.dom.svg
{

    public interface SVGAnimatedAngle
    {
        // SVGAnimatedAngle
        SVGAngle baseVal {get;}
        SVGAngle animVal {get;}
    }

}