//AutoGenerated

namespace org.w3c.dom.svg
{

    public interface SVGCursorElement : SVGElement, SVGURIReference, SVGTests, SVGExternalResourcesRequired
    {
        // SVGCursorElement
        SVGAnimatedLength x {get;}
        SVGAnimatedLength y {get;}
    }

}