using SharpKit.JavaScript;
//AutoGenerated

namespace org.w3c.dom.svg
{

    public interface SVGDescElement : SVGElement, SVGLangSpace, SVGStylable
    {
        // SVGDescElement
    }

}
