using SharpKit.JavaScript;
//AutoGenerated

namespace org.w3c.dom.svg
{

    public interface SVGElementInstanceList
    {
        // SVGElementInstanceList
        int length {get;}
        [JsProperty(NativeIndexer = true)]
        SVGElementInstance this[int index] { get; }
    }

}
