using SharpKit.JavaScript;
//AutoGenerated

namespace org.w3c.dom.svg
{

    public interface SVGFETileElement : SVGElement, SVGFilterPrimitiveStandardAttributes
    {
        // SVGFETileElement
        SVGAnimatedString in1 {get;}
    }

}
