//AutoGenerated

namespace org.w3c.dom.svg
{

    public interface SVGFEGaussianBlurElement : SVGElement, SVGFilterPrimitiveStandardAttributes
    {
        // SVGFEGaussianBlurElement
        SVGAnimatedString in1 {get;}
        SVGAnimatedNumber stdDeviationX {get;}
        SVGAnimatedNumber stdDeviationY {get;}
        void setStdDeviation(float stdDeviationX, float stdDeviationY);
    }

}