//AutoGenerated

namespace org.w3c.dom.svg
{

    public interface SVGFEComponentTransferElement : SVGElement, SVGFilterPrimitiveStandardAttributes
    {
        // SVGFEComponentTransferElement
        SVGAnimatedString in1 {get;}
    }

}