//Generated by a tool of Sebastian Loncar

namespace org.w3c.dom.svg
{

using SharpKit.JavaScript;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields=true, OmitCasts = true)]
public partial class SVGFilterPrimitiveStandardAttributes : SVGStylable
{

	// SVGFilterPrimitiveStandardAttributes
	public SVGAnimatedLength x {get { return default(SVGAnimatedLength); } }
	public SVGAnimatedLength y {get { return default(SVGAnimatedLength); } }
	public SVGAnimatedLength width {get { return default(SVGAnimatedLength); } }
	public SVGAnimatedLength height {get { return default(SVGAnimatedLength); } }
	public SVGAnimatedString result {get { return default(SVGAnimatedString); } }
}

}