using SharpKit.JavaScript;
//AutoGenerated

namespace org.w3c.dom.svg
{

    using DOMException = org.w3c.dom.DOMException;

    public interface SVGLengthList
    {
        // SVGLengthList
        int numberOfItems {get;}
//TODO:
//ORIGINAL LINE: public void clear() throws org.w3c.dom.DOMException;
        void clear();
//TODO:
//ORIGINAL LINE: public SVGLength initialize(SVGLength newItem) throws org.w3c.dom.DOMException, SVGException;
        SVGLength initialize(SVGLength newItem);
//TODO:
//ORIGINAL LINE: public SVGLength getItem(int index) throws org.w3c.dom.DOMException;
        SVGLength getItem(int index);
//TODO:
//ORIGINAL LINE: public SVGLength insertItemBefore(SVGLength newItem, int index) throws org.w3c.dom.DOMException, SVGException;
        SVGLength insertItemBefore(SVGLength newItem, int index);
//TODO:
//ORIGINAL LINE: public SVGLength replaceItem(SVGLength newItem, int index) throws org.w3c.dom.DOMException, SVGException;
        SVGLength replaceItem(SVGLength newItem, int index);
//TODO:
//ORIGINAL LINE: public SVGLength removeItem(int index) throws org.w3c.dom.DOMException;
        SVGLength removeItem(int index);
//TODO:
//ORIGINAL LINE: public SVGLength appendItem(SVGLength newItem) throws org.w3c.dom.DOMException, SVGException;
        SVGLength appendItem(SVGLength newItem);
    }

}
