//AutoGenerated

namespace org.w3c.dom.svg
{

    public interface SVGPathSegLinetoAbs : SVGPathSeg
    {
        // SVGPathSegLinetoAbs
        float x {get;set;}
        float y {get;set;}
    }

}