//AutoGenerated

namespace org.w3c.dom.svg
{

    public interface SVGPolylineElement : SVGElement, SVGTests, SVGLangSpace, SVGExternalResourcesRequired, SVGStylable, SVGTransformable, SVGAnimatedPoints
    {
        // SVGPolylineElement
    }

}