//AutoGenerated

namespace org.w3c.dom.svg
{

    public interface SVGPathSegArcAbs : SVGPathSeg
    {
        // SVGPathSegArcAbs
        float x {get;set;}
        float y {get;set;}
        float r1 {get;set;}
        float r2 {get;set;}
        float angle {get;set;}
        bool largeArcFlag {get;set;}
        bool sweepFlag {get;set;}
    }

}