// Generated by SharpKit.QooxDoo.Generator
using System;
using System.Collections.Generic;
using SharpKit.Html;
using SharpKit.JavaScript;

namespace qx.ui.table.cellrenderer
{
    /// <summary>
	/// <para>A template class for cell renderer, which display images. Concrete
	/// implementations must implement the method <see cref="#_identifyImage"/>.</para>
	/// </summary>
	[JsType(JsMode.Prototype, Name = "qx.ui.table.cellrenderer.AbstractImage", OmitOptionalParameters = true, Export = false)]
    public partial class AbstractImage : qx.ui.table.cellrenderer.Abstract
    {
		#region Properties

		/// <summary>
		/// <para>Whether to repeat or scale the image.</para>
		/// </summary>
		[JsProperty(Name = "repeat", NativeField = true)]
		public object Repeat { get; set; }

		#endregion Properties

		#region Methods

		public AbstractImage() { throw new NotImplementedException(); }

		[JsMethod(Name = "createDataCellHtml")]
		public void CreateDataCellHtml(object cellInfo, object htmlArr) { throw new NotImplementedException(); }

		/// <summary>
		/// <para>Returns the (computed) value of the property repeat.</para>
		/// </summary>
		[JsMethod(Name = "getRepeat")]
		public object GetRepeat() { throw new NotImplementedException(); }

		/// <summary>
		/// <para>Calls the apply method and dispatches the change event of the property repeat
		/// with the default value defined by the class developer. This function can
		/// only be called from the constructor of a class.</para>
		/// </summary>
		/// <param name="value">Initial value for property repeat.</param>
		[JsMethod(Name = "initRepeat")]
		public void InitRepeat(object value) { throw new NotImplementedException(); }

		/// <summary>
		/// <para>Resets the user value of the property repeat.</para>
		/// <para>The computed value falls back to the next available value e.g. appearance, init or
		/// inheritance value depeneding on the property configuration and value availability.</para>
		/// </summary>
		[JsMethod(Name = "resetRepeat")]
		public void ResetRepeat() { throw new NotImplementedException(); }

		/// <summary>
		/// <para>Sets the user value of the property repeat.</para>
		/// </summary>
		/// <param name="value">New value for property repeat.</param>
		[JsMethod(Name = "setRepeat")]
		public void SetRepeat(object value) { throw new NotImplementedException(); }

		#endregion Methods
    }
}