//Generated by a tool of Sebastian Loncar

namespace SharpKit.Html
{

using SharpKit.JavaScript;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields = true, OmitCasts = true)]
public partial class CharacterDataEditVAL : NodeEditVAL
{

	// CharacterDataEditVAL
	public short isWhitespaceOnly() { return default(short); }
	public short canSetData(string arg) { return default(short); }
	public short canAppendData(string arg) { return default(short); }
	public short canReplaceData(int offset, int count, string arg) { return default(short); }
	public short canInsertData(int offset, string arg) { return default(short); }
	public short canDeleteData(int offset, int count) { return default(short); }
}

}