using SharpKit.JavaScript;
//AutoGenerated

namespace org.w3c.dom.webdatabase
{

    public interface SQLResultSet
    {
        // SQLResultSet
        int insertId {get;}
        int rowsAffected {get;}
        SQLResultSetRowList rows {get;}
    }

}
