//AutoGenerated

namespace org.w3c.dom
{

    public interface ByteArray
    {
        // ByteArray
        int length {get;set;}
        sbyte getElement(int index);
        void setElement(int index, sbyte value);
    }

}