//AutoGenerated

namespace org.w3c.dom
{

    public interface DocumentFragment : Node
    {
        // DocumentFragment
        // NodeSelector
        Element querySelector(string selectors);
        NodeList querySelectorAll(string selectors);
    }

}