//Generated by a tool of Sebastian Loncar

namespace org.w3c.dom
{

using SharpKit.JavaScript;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields=true, OmitCasts = true)]
public partial class Entity : Node
{

	// Entity
	public string publicId {get { return default(string); } }
	public string systemId {get { return default(string); } }
	public string notationName {get { return default(string); } }
	public string inputEncoding {get { return default(string); } }
	public string xmlEncoding {get { return default(string); } }
	public string xmlVersion {get { return default(string); } }
}

}