//Generated by a tool of Sebastian Loncar

namespace org.w3c.dom
{

using SharpKit.JavaScript;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields=true, OmitCasts = true)]
public partial class LongArray
{

	// LongArray
	public int length {get;set;}
	public int getElement(int index) { return default(int); }
	public void setElement(int index, int value) {}
}

}