using SharpKit.JavaScript;
//AutoGenerated

namespace org.w3c.dom
{

    public interface NameList
    {
        // NameList
        JsString getName(int index);
        JsString getNamespaceURI(int index);
        int length {get;}
        bool contains(string str);
        bool containsNS(string namespaceURI, JsString name);
    }

}
