//Generated by a tool of Sebastian Loncar

namespace org.w3c.dom
{

using SharpKit.JavaScript;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields=true, OmitCasts = true)]
public partial class XMLHttpRequestUpload : XMLHttpRequestEventTarget
{

	// XMLHttpRequestUpload
}

}