/*Generated by SharpKit 5 v4.29.7000*/
var combobox = $("#products").data("kendoComboBox");
$(OnReady);
function OnReady()
{
    var data= [{text:"12 Angry Men",value:"1"},{text:"Il buono, il brutto, il cattivo.",value:"2"},{text:"Inception",value:"3"},{text:"One Flew Over the Cuckoo\'s Nest",value:"4"},{text:"Pulp Fiction",value:"5"},{text:"Schindler\'s List",value:"6"},{text:"The Dark Knight",value:"7"},{text:"The Godfather",value:"8"},{text:"The Godfather = Part II",value:"9"},{text:"The Shawshank Redemption",value:"10"},{text:"The Shawshank Redemption 2",value:"11"}];
    $("#products").kendoComboBox({dataTextField:"text",dataValueField:"value",dataSource:data}).closest(".k-widget").attr("id","products_wrapper");
    $("#filter").kendoDropDownList({change:filterTypeOnChanged});
    var setValue=function(e)
    {
        if(e !== "keypress")
        {
            var index=System.Int32.Parse$$String($("#index").val());
            combobox.select(index);
        }
    };
    var setIndex=function(e)
    {
         if (e.type != 'keypress' || kendo.keys.ENTER == e.keyCode) { var index = parseInt($('#index').val());combobox.select(index);};
    };
    var setSearch=function(e)
    {
         if (e.type != 'keypress' || kendo.keys.ENTER == e.keyCode) combobox.search($('#word').val());;
    };
    $("#enable").click(function()
    {
        combobox.enable();
    });
    $("#disable").click(function()
    {
        combobox.enable(false);
    });
    $("#open").click(function()
    {
        combobox.open();
    });
    $("#close").click(function()
    {
        combobox.close();
    });
    $("#getValue").click(function()
    {
        window.alert(combobox.value());
    });
    $("#getText").click(function()
    {
        window.alert(combobox.value());
    });
    $("#setValue").click(setValue);
    $("#value").keypress(setValue);
    $("#select").click(setIndex);
    $("#index").keypress(setIndex);
    $("#find").click(setSearch);
    $("#word").keypress(setSearch);
};
function filterTypeOnChanged()
{
     combobox.options.filter = $('#filter').val();;
};
