/*Generated by SharpKit 5 v4.30.1000*/
$(OnReady);
function OnReady()
{
    $("#spinner").spinner(
    {
        spin: function (e, ui)
        {
            if (ui.value > 10)
            {
                $(this).spinner("value", -10);
                return false;
            }
            else if (ui.value < -10)
            {
                $(this).spinner("value", 10);
                return false;
            }
        }
    });
};
