//AutoGenerated

namespace org.w3c.dom.validation
{

    using DOMConfiguration = org.w3c.dom.DOMConfiguration;
    using DOMException = org.w3c.dom.DOMException;
    using NameList = org.w3c.dom.NameList;

    public interface DocumentEditVAL : NodeEditVAL
    {
        // DocumentEditVAL
        bool continuousValidityChecking {get;set;}
//JAVA TO C# CONVERTER WARNING: Method 'throws' clauses are not available in .NET:
//ORIGINAL LINE: public void setContinuousValidityChecking(boolean continuousValidityChecking) throws org.w3c.dom.DOMException, ExceptionVAL;
        DOMConfiguration domConfig {get;}
        NameList getDefinedElements(string namespaceURI);
        short validateDocument();
    }

}