//***************************************************
//* This file was generated by tool
//* 20/07/2011 18:51:11
//* SharpKit
//***************************************************
using SharpKit.JavaScript;
#region Ext.form.action
namespace Ext.form.action
{
    #region StandardSubmit
    /// <summary>
    /// A class which handles submission of data from Forms using a standard
    /// &amp;lt;form&amp;gt; element submit. It does not handle the response from the submit. If validation of the form fields fails, the Form&#39;s Ext.form.Basic.afterAction method
    /// will be called. Otherwise, afterAction will not be called. Instances of this class are only created by a Form when
    /// submitting, when the form&#39;s Ext.form.Basic.standardSubmit
    /// config option is true.
    /// </summary>
    [JsType(JsMode.Prototype, Export=false)]
    public partial class StandardSubmit : Submit
    {
    }
    #endregion
    #region StandardSubmitConfig
    [JsType(JsMode.Json, Export=false)]
    public partial class StandardSubmitConfig
    {
        /// <summary>
        /// Optional target attribute to be used for the form when submitting. ...
        /// </summary>
        public JsString target{get;set;}
    }
    #endregion
    #region StandardSubmitEvents
    [JsType(JsMode.Json, Export=false)]
    public partial class StandardSubmitEvents
    {
    }
    #endregion
}
#endregion
