//***************************************************
//* This file was generated by tool
//* SharpKit
//***************************************************
using SharpKit.JavaScript;
#region Ext.fx.target
namespace Ext.fx.target
{
    #region Element
    /// <summary>
    /// This class represents a animation target for an Ext.core.Element. In general this class will not be
    /// created directly, the Ext.core.Element will be passed to the animation and
    /// and the appropriate target will be created.
    /// </summary>
    [JsType(JsMode.Prototype, Export=false)]
    public partial class Element : Target
    {
        public Element(Ext.fx.target.ElementConfig config){}
        public Element(){}
    }
    #endregion
    #region ElementConfig
    [JsType(JsMode.Json, Export=false)]
    public partial class ElementConfig : TargetConfig
    {
    }
    #endregion
    #region ElementEvents
    [JsType(JsMode.Json, Export=false)]
    public partial class ElementEvents : TargetEvents
    {
    }
    #endregion
}
#endregion
