//***************************************************
//* This file was generated by tool
//* 20/07/2011 17:29:50
//* SharpKit
//***************************************************
using SharpKit.JavaScript;
#region Ext.tip
namespace Ext.tip
{
    #region QuickTip
    /// <summary>
    /// A specialized tooltip class for tooltips that can be specified in markup and automatically managed by the global
    /// Ext.tip.QuickTipManager instance.  See the QuickTipManager class header for additional usage details and examples.
    /// </summary>
    [JsType(JsMode.Prototype, Export=false)]
    public partial class QuickTip : ToolTip, Ext.util.Floating, Ext.util.Observable, Ext.util.Animate, Ext.state.Stateful
    {
    }
    #endregion
    #region QuickTipConfig
    [JsType(JsMode.Json, Export=false)]
    public partial class QuickTipConfig
    {
        public bool interceptTitles{get;set;}
        public object target{get;set;}
    }
    #endregion
    #region QuickTipEvents
    [JsType(JsMode.Json, Export=false)]
    public partial class QuickTipEvents
    {
    }
    #endregion
}
#endregion
