//***************************************************
//* This file was generated by tool
//* 20/07/2011 17:29:50
//* SharpKit
//***************************************************
using SharpKit.JavaScript;
#region Ext.fx.target
namespace Ext.fx.target
{
    #region CompositeElement
    /// <summary>
    /// This class represents a animation target for a Ext.CompositeElement. It allows
    /// each Ext.core.Element in the group to be animated as a whole. In general this class will not be
    /// created directly, the Ext.CompositeElement will be passed to the animation and
    /// and the appropriate target will be created.
    /// </summary>
    [JsType(JsMode.Prototype, Export=false)]
    public partial class CompositeElement : Ext.fx.target.Element
    {
    }
    #endregion
    #region CompositeElementConfig
    [JsType(JsMode.Json, Export=false)]
    public partial class CompositeElementConfig
    {
    }
    #endregion
    #region CompositeElementEvents
    [JsType(JsMode.Json, Export=false)]
    public partial class CompositeElementEvents
    {
    }
    #endregion
}
#endregion
