//***************************************************
//* This file was generated by tool
//* 20/07/2011 19:12:24
//* SharpKit
//***************************************************
using SharpKit.JavaScript;
#region Ext.dd
namespace Ext.dd
{
    #region Registry
    /// <summary>
    /// Provides easy access to all drag drop components that are registered on a page.  Items can be retrieved either
    /// directly by DOM node id, or by passing in the drag drop event that occurred and looking up the event target.
    /// </summary>
    [JsType(JsMode.Prototype, Export=false)]
    public partial class Registry : Ext.Base
    {
        /// <summary>
        /// Returns the handle registered for a DOM Node by id ...
        /// </summary>
        public object getHandle(object id){return null;}
        /// <summary>
        /// Returns the handle that is registered for the DOM node that is the target of the event ...
        /// </summary>
        public object getHandleFromEvent(Event e){return null;}
        /// <summary>
        /// Returns a custom data object that is registered for a DOM node by id ...
        /// </summary>
        public object getTarget(object id){return null;}
        /// <summary>
        /// Returns a custom data object that is registered for the DOM node that is the target of the event ...
        /// </summary>
        public object getTargetFromEvent(Event e){return null;}
        /// <summary>
        /// Resgister a drag drop element ...
        /// </summary>
        public object register(object element, object data=null){return null;}
        /// <summary>
        /// Unregister a drag drop element ...
        /// </summary>
        public object unregister(object element){return null;}
    }
    #endregion
    #region RegistryConfig
    [JsType(JsMode.Json, Export=false)]
    public partial class RegistryConfig : Ext.BaseConfig
    {
    }
    #endregion
    #region RegistryEvents
    [JsType(JsMode.Json, Export=false)]
    public partial class RegistryEvents : Ext.BaseEvents
    {
    }
    #endregion
}
#endregion
