//***************************************************
//* This file was generated by tool
//* 20/07/2011 20:05:54
//* SharpKit
//***************************************************
using SharpKit.JavaScript;
#region Ext.picker
namespace Ext.picker
{
    #region Time
    /// <summary>
    /// A time picker which provides a list of times from which to choose. This is used by the
    /// Ext.form.field.Time class to allow browsing and selection of valid times, but could also be used
    /// with other components. By default, all times starting at midnight and incrementing every 15 minutes will be presented.
    /// This list of available times can be controlled using the minValue, maxValue, and
    /// increment configuration properties. The format of the times presented in the list can be
    /// customized with the format config. To handle when the user selects a time from the list, you can subscribe to the selectionchange
    /// event.  Code  new Ext.create(&#39;Ext.picker.Time&#39;, {
    /// width: 60,
    /// minValue: Ext.Date.parse(&#39;04:30:00 AM&#39;, &#39;h:i:s A&#39;),
    /// maxValue: Ext.Date.parse(&#39;08:00:00 AM&#39;, &#39;h:i:s A&#39;),
    /// renderTo: Ext.getBody()
    /// });
    /// </summary>
    [JsType(JsMode.Prototype, Export=false)]
    public partial class Time : Ext.view.BoundList, Ext.util.Floating, Ext.util.Observable, Ext.util.Animate, Ext.state.Stateful
    {
        /// <summary>
        /// Set the maxValue and update the list of available times. ...
        /// </summary>
        public object setMaxValue(JsDate value){return null;}
        /// <summary>
        /// Set the minValue and update the list of available times. ...
        /// </summary>
        public object setMinValue(JsDate value){return null;}
        /// <summary>
        /// Update the list of available times in the list to be constrained within the
        /// minValue and maxValue. ...
        /// </summary>
        public object updateList(){return null;}
        public Time(Ext.picker.TimeConfig config){}
        public Time(){}
    }
    #endregion
    #region TimeConfig
    [JsType(JsMode.Json, Export=false)]
    public partial class TimeConfig : Ext.view.BoundListConfig
    {
        /// <summary>
        /// The default time format string which can be overriden for localization support. ...
        /// </summary>
        public JsString format{get;set;}
        public JsNumber increment{get;set;}
        /// <summary>
        /// The maximum time to be shown in the list of times. ...
        /// </summary>
        public JsDate maxValue{get;set;}
        /// <summary>
        /// The minimum time to be shown in the list of times. ...
        /// </summary>
        public JsDate minValue{get;set;}
    }
    #endregion
    #region TimeEvents
    [JsType(JsMode.Json, Export=false)]
    public partial class TimeEvents : Ext.view.BoundListEvents
    {
    }
    #endregion
}
#endregion
