//***************************************************
//* This file was generated by tool
//* 20/07/2011 17:29:50
//* SharpKit
//***************************************************
using SharpKit.JavaScript;
#region Ext.resizer
namespace Ext.resizer
{
    #region Handle
    /// <summary>
    /// Provides a handle for 9-point resizing of Elements or Components.
    /// </summary>
    [JsType(JsMode.Prototype, Export=false)]
    public partial class Handle : Ext.Component, Ext.util.Floating, Ext.util.Observable, Ext.util.Animate, Ext.state.Stateful
    {
    }
    #endregion
    #region HandleConfig
    [JsType(JsMode.Json, Export=false)]
    public partial class HandleConfig
    {
    }
    #endregion
    #region HandleEvents
    [JsType(JsMode.Json, Export=false)]
    public partial class HandleEvents
    {
    }
    #endregion
}
#endregion
