/*Generated by SharpKit 5 v4.29.7000*/
$(OnReady);
function OnReady()
{
    $("#button").click(function(e)
    {
        $("#effect").toggleClass("newClass",1000);
        return false;
    });
};
