//Generated by a tool of Sebastian Loncar

namespace SharpKit.Html
{

using SharpKit.JavaScript;

[JsType(JsMode.Prototype, Export = false, PropertiesAsFields = true, OmitCasts = true)]
public partial class SVGAltGlyphElement : SVGTextPositioningElement
{

	// SVGAltGlyphElement
	public JsString glyphRef {get; set; }
	public JsString format {get; set; }
}

}