/*Generated by SharpKit 5 v5.00.0000*/
$(OnReady);
function OnReady()
{
    $("#button").click(function (e)
    {
        $("#effect").removeClass("newClass", 1000, callback);
        return false;
    });
};
function callback(e, ui)
{
    window.setTimeout(function ()
    {
        $("#effect").addClass("newClass");
    }, 1500);
};
